{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/zendeskcoresdk\/helpcenterutil\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil\/init","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicHelpCenterUtil(im)init","modules":[{"name":"ZendeskCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil"]]},"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/HelpCenterUtil":{"role":"symbol","title":"HelpCenterUtil","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HelpCenterUtil"}],"abstract":[{"type":"text","text":"Utility to add auth headers to content requests for restricted Help Centers"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HelpCenterUtil"}],"url":"\/documentation\/zendeskcoresdk\/helpcenterutil"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"role":"collection","title":"ZendeskCoreSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/HelpCenterUtil/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/zendeskcoresdk\/helpcenterutil\/init"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1HelpCenterUtil\/title","value":"ZDKClassicHelpCenterUtil"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1HelpCenterUtil\/fragments","value":[{"kind":"identifier","text":"ZDKClassicHelpCenterUtil"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}