{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"guid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/zendeskcoresdk\/zdkobjcanonymous\/guid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendeskcoresdk\/zdkobjcanonymous\/guid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCAnonymous\/guid","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"guid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"guid","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKObjCAnonymous(py)guid","modules":[{"name":"ZendeskCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"guid"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCAnonymous"]]},"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKObjCAnonymous":{"role":"symbol","title":"ZDKObjCAnonymous","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKObjCAnonymous"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCAnonymous","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKObjCAnonymous"}],"url":"\/documentation\/zendeskcoresdk\/zdkobjcanonymous"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"role":"collection","title":"ZendeskCoreSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKObjCAnonymous/guid":{"role":"symbol","title":"guid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"guid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCAnonymous\/guid","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"guid"}],"url":"\/documentation\/zendeskcoresdk\/zdkobjcanonymous\/guid"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"guid"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"guid"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"guid"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCAnonymous\/title","value":"ZDKObjCAnonymous"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCAnonymous\/fragments","value":[{"kind":"identifier","text":"ZDKObjCAnonymous"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCAnonymous~1guid\/title","value":"guid"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCAnonymous~1guid\/fragments","value":[{"kind":"identifier","text":"guid"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}