{"abstract":[{"text":"url of option","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserFieldOption"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserFieldOption\/url","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"url","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"url"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUserFieldOption(py)url","roleHeading":"Instance Property","modules":[{"name":"ZendeskCoreSDK"}],"title":"url"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"url"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/zendeskcoresdk\/userfieldoption\/url"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendeskcoresdk\/userfieldoption\/url"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"type":"topic","role":"collection","title":"ZendeskCoreSDK","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","abstract":[],"kind":"symbol","url":"\/documentation\/zendeskcoresdk"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/UserFieldOption":{"type":"topic","title":"UserFieldOption","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UserFieldOption","kind":"identifier"}],"abstract":[{"type":"text","text":"Dropdown userfields can contain User fields options which describe an option in the"},{"text":" ","type":"text"},{"type":"text","text":"dropdown"}],"role":"symbol","url":"\/documentation\/zendeskcoresdk\/userfieldoption","navigatorTitle":[{"text":"UserFieldOption","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserFieldOption"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/UserFieldOption/url":{"type":"topic","title":"url","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"url"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"url of option"}],"role":"symbol","url":"\/documentation\/zendeskcoresdk\/userfieldoption\/url","navigatorTitle":[{"kind":"identifier","text":"url"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserFieldOption\/url"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"url","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"url","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"url"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"ZDKClassicUserFieldOption","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserFieldOption\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKClassicUserFieldOption"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserFieldOption\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserFieldOption~1url\/title","value":"url"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserFieldOption~1url\/fragments","value":[{"text":"url","kind":"identifier"}]}]}]}