{"kind":"symbol","abstract":[{"text":"Tags associated with the user.","type":"text"}],"metadata":{"modules":[{"name":"ZendeskCoreSDK"}],"role":"symbol","title":"tags","navigatorTitle":[{"text":"tags","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"tags","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUser(py)tags"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/tags"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tags","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendeskcoresdk\/user\/tags"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendeskcoresdk\/user\/tags"]}],"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"type":"topic","role":"collection","title":"ZendeskCoreSDK","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","abstract":[],"kind":"symbol","url":"\/documentation\/zendeskcoresdk"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/User/tags":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"tags","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/zendeskcoresdk\/user\/tags","kind":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/tags","navigatorTitle":[{"text":"tags","kind":"identifier"}],"abstract":[{"type":"text","text":"Tags associated with the user."}],"title":"tags","role":"symbol","type":"topic"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/User":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"User"}],"navigatorTitle":[{"kind":"identifier","text":"User"}],"title":"User","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User","abstract":[{"type":"text","text":"A user in Zendesk."}],"kind":"symbol","url":"\/documentation\/zendeskcoresdk\/user"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"tags"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"tags"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"text":"tags","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User~1tags\/title","value":"tags","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User~1tags\/fragments","op":"replace","value":[{"text":"tags","kind":"identifier"}]},{"op":"replace","value":"ZDKClassicUser","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User\/fragments","op":"replace","value":[{"text":"ZDKClassicUser","kind":"identifier"}]}]}]}