{"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/SQ","doc:\/\/com.zendesk.ZendeskCoreSDK\/SH","doc:\/\/com.zendesk.ZendeskCoreSDK\/SY"],"type":"conformsTo","kind":"relationships"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel"},"metadata":{"symbolKind":"enum","modules":[{"name":"ZendeskCoreSDK"}],"title":"LogLevel","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LogLevel"}],"navigatorTitle":[{"text":"LogLevel","kind":"identifier"}],"externalID":"c:@M@ZendeskCoreSDK@E@ZDKClassicLogLevel","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKClassicLogLevel) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LogLevel","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendeskcoresdk\/loglevel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendeskcoresdk\/loglevel"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK"]]},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/debug","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/error","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/info","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/verbose","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/warn"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/init(rawValue:)"]},{"generated":true,"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/Equatable-Implementations","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/LogLevel/warn":{"navigatorTitle":[{"kind":"identifier","text":"ZDKClassicLogLevelWarn"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/warn","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"warn","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/zendeskcoresdk\/loglevel\/warn","title":"LogLevel.warn"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","kind":"symbol","url":"\/documentation\/zendeskcoresdk","abstract":[],"title":"ZendeskCoreSDK"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/LogLevel/Equatable-Implementations":{"type":"topic","role":"collectionGroup","title":"Equatable Implementations","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/Equatable-Implementations","kind":"article","abstract":[],"url":"\/documentation\/zendeskcoresdk\/loglevel\/equatable-implementations"},"doc://com.zendesk.ZendeskCoreSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/LogLevel":{"abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel","navigatorTitle":[{"text":"LogLevel","kind":"identifier"}],"title":"LogLevel","url":"\/documentation\/zendeskcoresdk\/loglevel","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LogLevel","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/LogLevel/error":{"navigatorTitle":[{"kind":"identifier","text":"ZDKClassicLogLevelError"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/error","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/zendeskcoresdk\/loglevel\/error","title":"LogLevel.error"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/LogLevel/init(rawValue:)":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/init(rawValue:)","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"url":"\/documentation\/zendeskcoresdk\/loglevel\/init(rawvalue:)","title":"init(rawValue:)"},"doc://com.zendesk.ZendeskCoreSDK/SY":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/SY","title":"Swift.RawRepresentable"},"doc://com.zendesk.ZendeskCoreSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/SH","title":"Swift.Hashable"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/LogLevel/RawRepresentable-Implementations":{"abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","type":"topic","url":"\/documentation\/zendeskcoresdk\/loglevel\/rawrepresentable-implementations","kind":"article","role":"collectionGroup"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/LogLevel/debug":{"type":"topic","navigatorTitle":[{"text":"ZDKClassicLogLevelDebug","kind":"identifier"}],"title":"LogLevel.debug","abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/debug","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debug","kind":"identifier"}],"url":"\/documentation\/zendeskcoresdk\/loglevel\/debug","role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/LogLevel/info":{"navigatorTitle":[{"kind":"identifier","text":"ZDKClassicLogLevelInfo"}],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"info","kind":"identifier"}],"abstract":[],"title":"LogLevel.info","role":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/info","url":"\/documentation\/zendeskcoresdk\/loglevel\/info"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/LogLevel/verbose":{"type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verbose"}],"url":"\/documentation\/zendeskcoresdk\/loglevel\/verbose","role":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/verbose","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKClassicLogLevelVerbose"}],"title":"LogLevel.verbose"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ZDKClassicLogLevel"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKClassicLogLevel","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ZDKClassicLogLevel","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/debug","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/error","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/info","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/verbose","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/warn"],"title":"Enumeration Cases"}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKClassicLogLevel"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel~1warn\/title","value":"ZDKClassicLogLevelWarn"},{"value":[{"kind":"identifier","text":"ZDKClassicLogLevelWarn"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel~1warn\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel\/title","op":"replace","value":"ZDKClassicLogLevel"},{"value":[{"kind":"identifier","text":"ZDKClassicLogLevel"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel\/fragments","op":"replace"},{"op":"replace","value":"ZDKClassicLogLevelError","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel~1error\/title"},{"value":[{"text":"ZDKClassicLogLevelError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel~1error\/fragments"},{"value":"ZDKClassicLogLevelDebug","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel~1debug\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel~1debug\/fragments","value":[{"kind":"identifier","text":"ZDKClassicLogLevelDebug"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel~1info\/title","value":"ZDKClassicLogLevelInfo"},{"op":"replace","value":[{"text":"ZDKClassicLogLevelInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel~1info\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel~1verbose\/title","op":"replace","value":"ZDKClassicLogLevelVerbose"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel~1verbose\/fragments","value":[{"kind":"identifier","text":"ZDKClassicLogLevelVerbose"}],"op":"replace"}]}]}