{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ZendeskCoreSDK\/s7CVarArgP","doc:\/\/com.zendesk.ZendeskCoreSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ZendeskCoreSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ZendeskCoreSDK\/SQ","doc:\/\/com.zendesk.ZendeskCoreSDK\/SH"],"type":"conformsTo","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKIdentityMigrator","kind":"identifier"}]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendeskcoresdk\/zdkidentitymigrator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendeskcoresdk\/zdkidentitymigrator"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKIdentityMigrator"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKIdentityMigrator\/init()"],"title":"Initializers"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKIdentityMigrator"}],"roleHeading":"Class","externalID":"c:objc(cs)ZDKIdentityMigrator","navigatorTitle":[{"text":"ZDKIdentityMigrator","kind":"identifier"}],"symbolKind":"class","title":"ZDKIdentityMigrator","modules":[{"name":"ZendeskCoreSDK"}],"role":"symbol"},"references":{"doc://com.zendesk.ZendeskCoreSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.ZendeskCoreSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.ZendeskCoreSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.ZendeskCoreSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/SH","title":"Swift.Hashable"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","kind":"symbol","url":"\/documentation\/zendeskcoresdk","abstract":[],"title":"ZendeskCoreSDK"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKIdentityMigrator/init()":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init()","kind":"symbol","url":"\/documentation\/zendeskcoresdk\/zdkidentitymigrator\/init()","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKIdentityMigrator\/init()","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKIdentityMigrator":{"navigatorTitle":[{"text":"ZDKIdentityMigrator","kind":"identifier"}],"title":"ZDKIdentityMigrator","kind":"symbol","url":"\/documentation\/zendeskcoresdk\/zdkidentitymigrator","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKIdentityMigrator","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKIdentityMigrator","kind":"identifier"}],"abstract":[]},"doc://com.zendesk.ZendeskCoreSDK/objc(cs)NSObject":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.zendesk.ZendeskCoreSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.zendesk.ZendeskCoreSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ZDKIdentityMigrator","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKIdentityMigrator"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKIdentityMigrator"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKIdentityMigrator\/init()"],"title":"Instance Methods"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKIdentityMigrator","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKIdentityMigrator~1init()\/title","op":"replace","value":"init"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKIdentityMigrator~1init()\/fragments"},{"op":"replace","value":"ZDKIdentityMigrator","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKIdentityMigrator\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKIdentityMigrator\/fragments","op":"replace","value":[{"text":"ZDKIdentityMigrator","kind":"identifier"}]}]}]}