{"metadata":{"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"position"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"position"}],"role":"symbol","externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUserFieldOption(py)position","modules":[{"name":"ZendeskCoreSDK"}],"title":"position"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"position of option","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendeskcoresdk\/userfieldoption\/position"]},{"paths":["\/documentation\/zendeskcoresdk\/userfieldoption\/position"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]}]}],"identifier":{"url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserFieldOption\/position","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserFieldOption"]]},"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/UserFieldOption":{"url":"\/documentation\/zendeskcoresdk\/userfieldoption","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserFieldOption","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserFieldOption","navigatorTitle":[{"text":"UserFieldOption","kind":"identifier"}],"kind":"symbol","title":"UserFieldOption","abstract":[{"text":"Dropdown userfields can contain User fields options which describe an option in the","type":"text"},{"type":"text","text":" "},{"text":"dropdown","type":"text"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"title":"ZendeskCoreSDK","url":"\/documentation\/zendeskcoresdk","type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","abstract":[]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/UserFieldOption/position":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"position","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/zendeskcoresdk\/userfieldoption\/position","kind":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserFieldOption\/position","title":"position","navigatorTitle":[{"text":"position","kind":"identifier"}],"abstract":[{"text":"position of option","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"position","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"position"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"text":"position","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserFieldOption\/title","value":"ZDKClassicUserFieldOption","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserFieldOption\/fragments","value":[{"kind":"identifier","text":"ZDKClassicUserFieldOption"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserFieldOption~1position\/title","value":"position","op":"replace"},{"value":[{"kind":"identifier","text":"position"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserFieldOption~1position\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}