{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(ZDKClassicIdentityType) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IdentityType"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendeskcoresdk\/identitytype"]},{"paths":["\/documentation\/zendeskcoresdk\/identitytype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/SQ","doc:\/\/com.zendesk.ZendeskCoreSDK\/SH","doc:\/\/com.zendesk.ZendeskCoreSDK\/SY"],"type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType"},"metadata":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdentityType"}],"modules":[{"name":"ZendeskCoreSDK"}],"roleHeading":"Enumeration","symbolKind":"enum","title":"IdentityType","externalID":"c:@M@ZendeskCoreSDK@E@ZDKClassicIdentityType","navigatorTitle":[{"text":"IdentityType","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType\/anonymous","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType\/jwt"]},{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType\/Equatable-Implementations","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/IdentityType/jwt":{"url":"\/documentation\/zendeskcoresdk\/identitytype\/jwt","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKClassicIdentityTypeJwt"}],"kind":"symbol","title":"IdentityType.jwt","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"jwt","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType\/jwt"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/IdentityType/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations","abstract":[],"role":"collectionGroup","type":"topic","url":"\/documentation\/zendeskcoresdk\/identitytype\/rawrepresentable-implementations"},"doc://com.zendesk.ZendeskCoreSDK/SH":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/IdentityType/Equatable-Implementations":{"url":"\/documentation\/zendeskcoresdk\/identitytype\/equatable-implementations","kind":"article","role":"collectionGroup","type":"topic","abstract":[],"title":"Equatable Implementations","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType\/Equatable-Implementations"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"title":"ZendeskCoreSDK","url":"\/documentation\/zendeskcoresdk","type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","abstract":[]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/IdentityType":{"kind":"symbol","url":"\/documentation\/zendeskcoresdk\/identitytype","role":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType","navigatorTitle":[{"text":"IdentityType","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IdentityType"}],"title":"IdentityType"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/IdentityType/init(rawValue:)":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType\/init(rawValue:)","title":"init(rawValue:)","kind":"symbol","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/zendeskcoresdk\/identitytype\/init(rawvalue:)"},"doc://com.zendesk.ZendeskCoreSDK/SQ":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.ZendeskCoreSDK/SY":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/IdentityType/anonymous":{"title":"IdentityType.anonymous","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"anonymous"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType\/anonymous","type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/zendeskcoresdk\/identitytype\/anonymous","role":"symbol","navigatorTitle":[{"text":"ZDKClassicIdentityTypeAnonymous","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"ZDKClassicIdentityType","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ZDKClassicIdentityType"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"ZDKClassicIdentityType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType\/anonymous","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType\/jwt"],"title":"Enumeration Cases"}],"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKClassicIdentityType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityType~1jwt\/title","value":"ZDKClassicIdentityTypeJwt","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityType~1jwt\/fragments","op":"replace","value":[{"text":"ZDKClassicIdentityTypeJwt","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityType\/title","value":"ZDKClassicIdentityType"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityType\/fragments","value":[{"kind":"identifier","text":"ZDKClassicIdentityType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityType~1anonymous\/title","value":"ZDKClassicIdentityTypeAnonymous","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityType~1anonymous\/fragments","value":[{"kind":"identifier","text":"ZDKClassicIdentityTypeAnonymous"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}