{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(ZDKClassicUser) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"User"}]}]}],"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"User","kind":"identifier"}],"modules":[{"name":"ZendeskCoreSDK"}],"externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUser","symbolKind":"class","title":"User","navigatorTitle":[{"kind":"identifier","text":"User"}],"roleHeading":"Class"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK"]]},"abstract":[{"type":"text","text":"A user in Zendesk."}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ZendeskCoreSDK\/s7CVarArgP","doc:\/\/com.zendesk.ZendeskCoreSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ZendeskCoreSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ZendeskCoreSDK\/Se","doc:\/\/com.zendesk.ZendeskCoreSDK\/SQ","doc:\/\/com.zendesk.ZendeskCoreSDK\/SH"],"kind":"relationships"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/init(from:)"]},{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/agent","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/content_url","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/id","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/name","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/tags","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/user_fields"],"title":"Instance Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendeskcoresdk\/user"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendeskcoresdk\/user"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.ZendeskCoreSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.ZendeskCoreSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/User/user_fields":{"url":"\/documentation\/zendeskcoresdk\/user\/user_fields","abstract":[{"text":"User fields for this user as a dictionary with the key being the name of the user field","type":"text"},{"text":" ","type":"text"},{"text":"and the corresponding value being the value of the user field set for this user.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"user_fields"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]","kind":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/user_fields","title":"user_fields","navigatorTitle":[{"text":"user_fields","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/User/agent":{"url":"\/documentation\/zendeskcoresdk\/user\/agent","abstract":[{"text":"Bool to indicate whether the user is an agent or not","type":"text"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/agent","title":"agent","role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"agent"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"agent","kind":"identifier"}],"type":"topic"},"doc://com.zendesk.ZendeskCoreSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.ZendeskCoreSDK/Se":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/Se","title":"Swift.Decodable"},"doc://com.zendesk.ZendeskCoreSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"title":"ZendeskCoreSDK","url":"\/documentation\/zendeskcoresdk","type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","abstract":[]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/User":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"User","kind":"identifier"}],"navigatorTitle":[{"text":"User","kind":"identifier"}],"abstract":[{"text":"A user in Zendesk.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User","url":"\/documentation\/zendeskcoresdk\/user","title":"User"},"doc://com.zendesk.ZendeskCoreSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/User/content_url":{"url":"\/documentation\/zendeskcoresdk\/user\/content_url","abstract":[{"type":"text","text":"The users content url"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"content_url","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/content_url","title":"content_url","navigatorTitle":[{"kind":"identifier","text":"content_url"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/User/tags":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/tags","url":"\/documentation\/zendeskcoresdk\/user\/tags","navigatorTitle":[{"text":"tags","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tags"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"title":"tags","abstract":[{"text":"Tags associated with the user.","type":"text"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/User/name":{"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"name","kind":"identifier"}],"abstract":[{"text":"The user’s name","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/name","url":"\/documentation\/zendeskcoresdk\/user\/name","title":"name"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/User/id":{"url":"\/documentation\/zendeskcoresdk\/user\/id","abstract":[{"type":"text","text":"The user’s id"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/id","title":"id","navigatorTitle":[{"text":"id","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/User/init(from:)":{"url":"\/documentation\/zendeskcoresdk\/user\/init(from:)","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier","text":"Decoder"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/init(from:)","title":"init(from:)"},"doc://com.zendesk.ZendeskCoreSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.ZendeskCoreSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"ZDKClassicUser","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKClassicUser","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKClassicUser"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/agent","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/content_url","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/id","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/name","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/tags","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/user_fields"]}]},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKClassicUser"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"user_fields","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User~1user_fields\/title"},{"op":"replace","value":[{"text":"user_fields","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User~1user_fields\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User~1agent\/title","value":"agent"},{"value":[{"kind":"identifier","text":"agent"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User~1agent\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User\/title","value":"ZDKClassicUser","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User\/fragments","value":[{"text":"ZDKClassicUser","kind":"identifier"}],"op":"replace"},{"value":"content_url","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User~1content_url\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User~1content_url\/fragments","value":[{"text":"content_url","kind":"identifier"}]},{"op":"replace","value":"tags","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User~1tags\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User~1tags\/fragments","op":"replace","value":[{"kind":"identifier","text":"tags"}]},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User~1name\/title","value":"name","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User~1name\/fragments","value":[{"text":"name","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User~1id\/title","value":"id","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User~1id\/fragments","value":[{"text":"id","kind":"identifier"}]}]}]}