{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk"},"metadata":{"navigatorTitle":[{"text":"Zendesk","kind":"identifier"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Zendesk","kind":"identifier"}],"roleHeading":"Class","title":"Zendesk","externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk","modules":[{"name":"ZendeskCoreSDK"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(ZDKClassicZendesk) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Zendesk"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/zendeskcoresdk\/zendesk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendeskcoresdk\/zendesk"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/AccessStatusProvider","doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ZendeskCoreSDK\/s7CVarArgP","doc:\/\/com.zendesk.ZendeskCoreSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ZendeskCoreSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ZendeskCoreSDK\/SQ","doc:\/\/com.zendesk.ZendeskCoreSDK\/SH"],"title":"Conforms To"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/accountDetails","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/actionHandlerRegistry","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/identity","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/identityType","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/providerModule","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/storeModule","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/zendeskUrl"]},{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/objCIdentity()","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/setIdentity(_:)-6ije2","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/setIdentity(_:)-xuv4"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/instance"],"title":"Type Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/initialize(appId:clientId:zendeskUrl:)"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/AccessStatusProvider-Implementations"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK"]]},"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/AccessStatusProvider":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/AccessStatusProvider","abstract":[],"url":"\/documentation\/zendeskcoresdk\/accessstatusprovider","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccessStatusProvider","kind":"identifier"}],"title":"AccessStatusProvider","kind":"symbol","navigatorTitle":[{"text":"AccessStatusProvider","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Zendesk/initialize(appId:clientId:zendeskUrl:)":{"url":"\/documentation\/zendeskcoresdk\/zendesk\/initialize(appid:clientid:zendeskurl:)","type":"topic","navigatorTitle":[{"text":"initializeWithAppId:clientId:zendeskUrl:","kind":"identifier"}],"kind":"symbol","title":"initialize(appId:clientId:zendeskUrl:)","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"text":"appId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"clientId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"zendeskUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/initialize(appId:clientId:zendeskUrl:)"},"doc://com.zendesk.ZendeskCoreSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/s7CVarArgP"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Zendesk/identity":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identity"},{"text":": ","kind":"text"},{"text":"Identity","kind":"typeIdentifier","preciseIdentifier":"s:14ZendeskCoreSDK8IdentityO"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/identity","title":"identity","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk\/zendesk\/identity","abstract":[],"role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(cs)NSObject"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Zendesk/providerModule":{"url":"\/documentation\/zendeskcoresdk\/zendesk\/providermodule","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"providerModule","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14ZendeskCoreSDK14ProviderModuleP","text":"ProviderModule"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/providerModule","title":"providerModule"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Zendesk/instance":{"url":"\/documentation\/zendeskcoresdk\/zendesk\/instance","title":"instance","type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/instance","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"instance","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk","text":"Zendesk","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"text":"instance","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"title":"ZendeskCoreSDK","url":"\/documentation\/zendeskcoresdk","type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","abstract":[]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Zendesk/objCIdentity()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"objCIdentity","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"ZDKObjCIdentity","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(pl)ZDKObjCIdentity"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"objCIdentity","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/objCIdentity()","title":"objCIdentity()","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk\/zendesk\/objcidentity()","abstract":[],"role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Zendesk/AccessStatusProvider-Implementations":{"role":"collectionGroup","type":"topic","url":"\/documentation\/zendeskcoresdk\/zendesk\/accessstatusprovider-implementations","kind":"article","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/AccessStatusProvider-Implementations","title":"AccessStatusProvider Implementations","abstract":[]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Zendesk/actionHandlerRegistry":{"url":"\/documentation\/zendeskcoresdk\/zendesk\/actionhandlerregistry","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"actionHandlerRegistry","kind":"identifier"},{"kind":"text","text":": "},{"text":"ActionHandlerRegistry","kind":"typeIdentifier","preciseIdentifier":"s:14ZendeskCoreSDK21ActionHandlerRegistryV"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/actionHandlerRegistry","title":"actionHandlerRegistry","abstract":[]},"doc://com.zendesk.ZendeskCoreSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Zendesk/setIdentity(_:)-6ije2":{"url":"\/documentation\/zendeskcoresdk\/zendesk\/setidentity(_:)-6ije2","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setIdentity"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:14ZendeskCoreSDK8IdentityO","text":"Identity"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/setIdentity(_:)-6ije2","title":"setIdentity(_:)","abstract":[]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Zendesk/storeModule":{"type":"topic","title":"storeModule","url":"\/documentation\/zendeskcoresdk\/zendesk\/storemodule","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"storeModule"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14ZendeskCoreSDK11StoreModuleP","text":"StoreModule"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/storeModule","role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/SQ"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Zendesk":{"type":"topic","title":"Zendesk","url":"\/documentation\/zendeskcoresdk\/zendesk","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Zendesk"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Zendesk"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk","role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Zendesk/setIdentity(_:)-xuv4":{"url":"\/documentation\/zendeskcoresdk\/zendesk\/setidentity(_:)-xuv4","title":"setIdentity(_:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/setIdentity(_:)-xuv4","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setIdentity","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(pl)ZDKObjCIdentity","kind":"typeIdentifier","text":"ZDKObjCIdentity"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"setIdentity:","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Zendesk/accountDetails":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/accountDetails","abstract":[],"url":"\/documentation\/zendeskcoresdk\/zendesk\/accountdetails","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"accountDetails","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14ZendeskCoreSDK14AccountDetailsP","text":"AccountDetails"}],"title":"accountDetails","kind":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Zendesk/zendeskUrl":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/zendeskUrl","url":"\/documentation\/zendeskcoresdk\/zendesk\/zendeskurl","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"zendeskUrl"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"zendeskUrl","kind":"identifier"}],"title":"zendeskUrl"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Zendesk/identityType":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identityType","kind":"identifier"},{"kind":"text","text":": "},{"text":"IdentityType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskCoreSDK@E@ZDKClassicIdentityType"}],"navigatorTitle":[{"kind":"identifier","text":"identityType"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/identityType","title":"identityType","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk\/zendesk\/identitytype","abstract":[],"role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/s28CustomDebugStringConvertibleP"},"doc://com.zendesk.ZendeskCoreSDK/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/SH"},"doc://com.zendesk.ZendeskCoreSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ZDKClassicZendesk","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKClassicZendesk"}],"op":"replace"},{"op":"replace","value":[{"text":"ZDKClassicZendesk","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/identityType","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/zendeskUrl"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/objCIdentity()","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/setIdentity(_:)-xuv4"]},{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/instance"]},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/initialize(appId:clientId:zendeskUrl:)"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKClassicZendesk"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk~1initialize(appId:clientId:zendeskUrl:)\/title","value":"initializeWithAppId:clientId:zendeskUrl:"},{"value":[{"text":"+ ","kind":"text"},{"text":"initializeWithAppId:clientId:zendeskUrl:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk~1initialize(appId:clientId:zendeskUrl:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk~1instance\/title","op":"replace","value":"instance"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk~1instance\/fragments","value":[{"kind":"identifier","text":"instance"}],"op":"replace"},{"value":"objCIdentity","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk~1objCIdentity()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk~1objCIdentity()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"objCIdentity","kind":"identifier"}]},{"op":"replace","value":"ZDKClassicZendesk","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk\/title"},{"value":[{"text":"ZDKClassicZendesk","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk\/fragments"},{"value":"setIdentity:","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk~1setIdentity(_:)-xuv4\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk~1setIdentity(_:)-xuv4\/fragments","value":[{"kind":"text","text":"- "},{"text":"setIdentity:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk~1zendeskUrl\/title","op":"replace","value":"zendeskUrl"},{"value":[{"kind":"identifier","text":"zendeskUrl"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk~1zendeskUrl\/fragments"},{"op":"replace","value":"identityType","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk~1identityType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk~1identityType\/fragments","value":[{"kind":"identifier","text":"identityType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}