{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"property","required":true,"role":"symbol","navigatorTitle":[{"text":"type","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IdentityType","preciseIdentifier":"c:@M@ZendeskCoreSDK@E@ZDKClassicIdentityType"}],"roleHeading":"Instance Property","title":"type","externalID":"c:@M@ZendeskCoreSDK@objc(pl)ZDKObjCIdentity(py)type","modules":[{"name":"ZendeskCoreSDK"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IdentityType","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType","preciseIdentifier":"c:@M@ZendeskCoreSDK@E@ZDKClassicIdentityType"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/zendeskcoresdk\/zdkobjcidentity\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendeskcoresdk\/zdkobjcidentity\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCIdentity"]]},"identifier":{"url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCIdentity\/type","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKObjCIdentity/type":{"required":true,"url":"\/documentation\/zendeskcoresdk\/zdkobjcidentity\/type","title":"type","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCIdentity\/type","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskCoreSDK@E@ZDKClassicIdentityType","text":"IdentityType"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"type"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"type":"topic","role":"collection","title":"ZendeskCoreSDK","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","abstract":[],"kind":"symbol","url":"\/documentation\/zendeskcoresdk"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKObjCIdentity":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKObjCIdentity"}],"abstract":[],"url":"\/documentation\/zendeskcoresdk\/zdkobjcidentity","title":"ZDKObjCIdentity","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCIdentity","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ZDKObjCIdentity","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/IdentityType":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType","title":"IdentityType","type":"topic","url":"\/documentation\/zendeskcoresdk\/identitytype","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"IdentityType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IdentityType"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"type","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"type"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ZDKClassicIdentityType","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType","preciseIdentifier":"c:@M@ZendeskCoreSDK@E@ZDKClassicIdentityType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCIdentity~1type\/title","op":"replace","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCIdentity~1type\/fragments","value":[{"kind":"identifier","text":"type"}]},{"value":"ZDKObjCIdentity","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCIdentity\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCIdentity\/fragments","value":[{"kind":"identifier","text":"ZDKObjCIdentity"}],"op":"replace"},{"value":"ZDKClassicIdentityType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityType\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityType\/fragments","value":[{"kind":"identifier","text":"ZDKClassicIdentityType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}