{"variants":[{"paths":["\/documentation\/zendeskcoresdk\/zendesk\/setidentity(_:)-xuv4"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendeskcoresdk\/zendesk\/setidentity(_:)-xuv4"]}],"kind":"symbol","metadata":{"externalID":"c:@CM@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk(im)setIdentity:","title":"setIdentity(_:)","navigatorTitle":[{"text":"setIdentity:","kind":"identifier"}],"extendedModule":"ZendeskCoreSDK","modules":[{"name":"ZendeskCoreSDK"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setIdentity","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"ZDKObjCIdentity","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(pl)ZDKObjCIdentity"},{"text":")","kind":"text"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setIdentity","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"newIdentity"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ZDKObjCIdentity","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCIdentity","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(pl)ZDKObjCIdentity"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/setIdentity(_:)-xuv4","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKObjCIdentity":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKObjCIdentity","kind":"identifier"}],"kind":"symbol","title":"ZDKObjCIdentity","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCIdentity","url":"\/documentation\/zendeskcoresdk\/zdkobjcidentity","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ZDKObjCIdentity"}],"role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Zendesk":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk","title":"Zendesk","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Zendesk"}],"role":"symbol","navigatorTitle":[{"text":"Zendesk","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/zendeskcoresdk\/zendesk","abstract":[]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Zendesk/setIdentity(_:)-xuv4":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"setIdentity:"}],"title":"setIdentity(_:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/setIdentity(_:)-xuv4","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setIdentity"},{"kind":"text","text":"("},{"text":"ZDKObjCIdentity","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(pl)ZDKObjCIdentity","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/zendeskcoresdk\/zendesk\/setidentity(_:)-xuv4"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","role":"collection","url":"\/documentation\/zendeskcoresdk","kind":"symbol","abstract":[],"title":"ZendeskCoreSDK"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"setIdentity:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setIdentity:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setIdentity:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@ZendeskCoreSDK@objc(pl)ZDKObjCIdentity","text":"id<ZDKObjCIdentity>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"newIdentity","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCIdentity\/title","value":"ZDKObjCIdentity","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCIdentity\/fragments","value":[{"kind":"identifier","text":"ZDKObjCIdentity"}]},{"value":"ZDKClassicZendesk","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk\/fragments","value":[{"kind":"identifier","text":"ZDKClassicZendesk"}]},{"value":"setIdentity:","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk~1setIdentity(_:)-xuv4\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk~1setIdentity(_:)-xuv4\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setIdentity:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}