{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKClassicPushProvider) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKPushProvider","kind":"identifier"}]}]}],"abstract":[{"type":"text","text":"An objective-c visible class for the Push Registration Provider"},{"type":"text","text":" "},{"type":"text","text":"Provider to register and unregister a device for push notifications."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ZendeskCoreSDK\/s7CVarArgP","doc:\/\/com.zendesk.ZendeskCoreSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ZendeskCoreSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ZendeskCoreSDK\/SQ","doc:\/\/com.zendesk.ZendeskCoreSDK\/SH"],"type":"conformsTo","kind":"relationships"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider\/init(zendesk:)"]},{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider\/register(UAIdentifier:locale:completion:)","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider\/register(deviceIdentifier:locale:completion:)","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider\/unregisterForPush()"],"title":"Instance Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendeskcoresdk\/zdkpushprovider"]},{"paths":["\/documentation\/zendeskcoresdk\/zdkpushprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK"]]},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider","interfaceLanguage":"swift"},"metadata":{"symbolKind":"class","modules":[{"name":"ZendeskCoreSDK"}],"title":"ZDKPushProvider","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKPushProvider","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKPushProvider","kind":"identifier"}],"role":"symbol","externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicPushProvider"},"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKPushProvider/register(UAIdentifier:locale:completion:)":{"type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider\/register(UAIdentifier:locale:completion:)","title":"register(UAIdentifier:locale:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"kind":"text","text":"("},{"text":"UAIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"locale","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"registerWithUAIdentifier:locale:completion:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/zendeskcoresdk\/zdkpushprovider\/register(uaidentifier:locale:completion:)","abstract":[{"type":"text","text":"Calls a push registration end point to register the given Urban Airship channel id."}]},"doc://com.zendesk.ZendeskCoreSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.ZendeskCoreSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.ZendeskCoreSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/SH","title":"Swift.Hashable"},"doc://com.zendesk.ZendeskCoreSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKPushProvider/init(zendesk:)":{"title":"init(zendesk:)","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider\/init(zendesk:)","url":"\/documentation\/zendeskcoresdk\/zdkpushprovider\/init(zendesk:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"zendesk","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk","kind":"typeIdentifier","text":"Zendesk"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithZendesk:"}],"role":"symbol","abstract":[{"type":"text","text":"Initialize the provider"}]},"doc://com.zendesk.ZendeskCoreSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.ZendeskCoreSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKPushProvider/unregisterForPush()":{"url":"\/documentation\/zendeskcoresdk\/zdkpushprovider\/unregisterforpush()","navigatorTitle":[{"kind":"identifier","text":"unregisterForPush"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider\/unregisterForPush()","title":"unregisterForPush()","kind":"symbol","abstract":[{"type":"text","text":"Calls a push unregister endpoint with the stored device identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unregisterForPush"},{"kind":"text","text":"()"}],"type":"topic"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKPushProvider":{"title":"ZDKPushProvider","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider","url":"\/documentation\/zendeskcoresdk\/zdkpushprovider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKPushProvider"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"ZDKPushProvider","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"An objective-c visible class for the Push Registration Provider"},{"text":" ","type":"text"},{"type":"text","text":"Provider to register and unregister a device for push notifications."}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKPushProvider/register(deviceIdentifier:locale:completion:)":{"abstract":[{"text":"Calls a push registration end point to register the given APNS device id.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/zendeskcoresdk\/zdkpushprovider\/register(deviceidentifier:locale:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"register","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"deviceIdentifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"locale","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"registerWithDeviceIdentifier:locale:completion:","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider\/register(deviceIdentifier:locale:completion:)","title":"register(deviceIdentifier:locale:completion:)"},"doc://com.zendesk.ZendeskCoreSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","url":"\/documentation\/zendeskcoresdk","kind":"symbol","title":"ZendeskCoreSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"ZDKClassicPushProvider","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKClassicPushProvider"}],"op":"replace"},{"op":"replace","value":[{"text":"ZDKClassicPushProvider","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider\/init(zendesk:)","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider\/register(UAIdentifier:locale:completion:)","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider\/register(deviceIdentifier:locale:completion:)","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider\/unregisterForPush()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKClassicPushProvider"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]}},{"value":"registerWithUAIdentifier:locale:completion:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKPushProvider~1register(UAIdentifier:locale:completion:)\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKPushProvider~1register(UAIdentifier:locale:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerWithUAIdentifier:locale:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKPushProvider~1init(zendesk:)\/title","value":"initWithZendesk:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKPushProvider~1init(zendesk:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithZendesk:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKPushProvider~1unregisterForPush()\/title","op":"replace","value":"unregisterForPush"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKPushProvider~1unregisterForPush()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"unregisterForPush","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKPushProvider\/title","value":"ZDKClassicPushProvider"},{"op":"replace","value":[{"text":"ZDKClassicPushProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKPushProvider\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKPushProvider~1register(deviceIdentifier:locale:completion:)\/title","op":"replace","value":"registerWithDeviceIdentifier:locale:completion:"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKPushProvider~1register(deviceIdentifier:locale:completion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"registerWithDeviceIdentifier:locale:completion:","kind":"identifier"}]}]}]}