{"identifier":{"url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil\/canonicalRequest(for:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil"]]},"metadata":{"symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"canonicalRequestFor:","kind":"identifier"}],"modules":[{"name":"ZendeskCoreSDK"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canonicalRequest"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSURLRequest","text":"NSURLRequest","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"NSURLRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLRequest"}],"roleHeading":"Type Method","externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicHelpCenterUtil(cm)canonicalRequestFor:","title":"canonicalRequest(for:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canonicalRequest"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"request"},{"text":": ","kind":"text"},{"text":"NSURLRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLRequest"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLRequest","text":"NSURLRequest"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/zendeskcoresdk\/helpcenterutil\/canonicalrequest(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendeskcoresdk\/helpcenterutil\/canonicalrequest(for:)"]}],"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","url":"\/documentation\/zendeskcoresdk","kind":"symbol","title":"ZendeskCoreSDK"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/HelpCenterUtil":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HelpCenterUtil","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil","kind":"symbol","type":"topic","role":"symbol","title":"HelpCenterUtil","navigatorTitle":[{"kind":"identifier","text":"HelpCenterUtil"}],"abstract":[{"text":"Utility to add auth headers to content requests for restricted Help Centers","type":"text"}],"url":"\/documentation\/zendeskcoresdk\/helpcenterutil"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/HelpCenterUtil/canonicalRequest(for:)":{"title":"canonicalRequest(for:)","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil\/canonicalRequest(for:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canonicalRequest"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLRequest","text":"NSURLRequest"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSURLRequest","text":"NSURLRequest","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"canonicalRequestFor:","kind":"identifier"}],"role":"symbol","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk\/helpcenterutil\/canonicalrequest(for:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"canonicalRequestFor:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"canonicalRequestFor:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)NSURLRequest","kind":"typeIdentifier","text":"NSURLRequest"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"canonicalRequestFor:"},{"kind":"text","text":"("},{"text":"NSURLRequest","preciseIdentifier":"c:objc(cs)NSURLRequest","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"request","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"ZDKClassicHelpCenterUtil","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1HelpCenterUtil\/title"},{"value":[{"text":"ZDKClassicHelpCenterUtil","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1HelpCenterUtil\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1HelpCenterUtil~1canonicalRequest(for:)\/title","op":"replace","value":"canonicalRequestFor:"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1HelpCenterUtil~1canonicalRequest(for:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"canonicalRequestFor:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}