{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"zendesk","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk","kind":"typeIdentifier","text":"Zendesk","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"zendesk","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An instance of the zendesk singleton"}]}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/zendeskcoresdk\/zdkuserprovider\/init(zendesk:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendeskcoresdk\/zdkuserprovider\/init(zendesk:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"title":"init(zendesk:)","modules":[{"name":"ZendeskCoreSDK"}],"role":"symbol","externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUserProvider(im)initWithZendesk:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"zendesk"},{"text":": ","kind":"text"},{"text":"Zendesk","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk"},{"kind":"text","text":")"}],"roleHeading":"Initializer","symbolKind":"init","navigatorTitle":[{"text":"initWithZendesk:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKUserProvider\/init(zendesk:)"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKUserProvider"]]},"abstract":[{"type":"text","text":"Initialize the provider"}],"kind":"symbol","references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKUserProvider":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKUserProvider","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKUserProvider","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKUserProvider","title":"ZDKUserProvider","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk\/zdkuserprovider","abstract":[{"text":"An objective-c visible class for the User Provider","type":"text"}],"role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Zendesk":{"type":"topic","title":"Zendesk","url":"\/documentation\/zendeskcoresdk\/zendesk","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Zendesk"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Zendesk"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk","role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKUserProvider/init(zendesk:)":{"title":"init(zendesk:)","type":"topic","abstract":[{"text":"Initialize the provider","type":"text"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKUserProvider\/init(zendesk:)","role":"symbol","url":"\/documentation\/zendeskcoresdk\/zdkuserprovider\/init(zendesk:)","navigatorTitle":[{"text":"initWithZendesk:","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"zendesk"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk","text":"Zendesk"},{"text":")","kind":"text"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"title":"ZendeskCoreSDK","url":"\/documentation\/zendeskcoresdk","type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithZendesk:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithZendesk:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithZendesk:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk","text":"ZDKClassicZendesk","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk"},{"text":" *) ","kind":"text"},{"text":"zendesk","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKUserProvider\/title","value":"ZDKClassicUserProvider","op":"replace"},{"value":[{"text":"ZDKClassicUserProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKUserProvider\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk\/title","value":"ZDKClassicZendesk"},{"value":[{"text":"ZDKClassicZendesk","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKUserProvider~1init(zendesk:)\/title","value":"initWithZendesk:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithZendesk:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKUserProvider~1init(zendesk:)\/fragments"}]}]}