{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKUserProvider"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setUserFields"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUser","text":"User"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":"))","kind":"text"}],"modules":[{"name":"ZendeskCoreSDK"}],"navigatorTitle":[{"text":"setUserFields:completion:","kind":"identifier"}],"title":"setUserFields(_:completion:)","symbolKind":"method","externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUserProvider(im)setUserFields:completion:","role":"symbol","roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKUserProvider\/setUserFields(_:completion:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setUserFields"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"userFields","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"text":" ((","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User","text":"User","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUser"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":"))","kind":"text"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"userfields: The user field to set.  It expects a dictionary(not a ZDKClassicUserField)."},{"type":"text","text":" "},{"text":"The key of this dictionary being the name of the user field and the corresponding value","type":"text"},{"type":"text","text":" "},{"text":"being the user field value to be set for the current user.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"completion: Returns a user object if successful with a nil for the error","type":"text"}]}]}]}]}],"sections":[],"abstract":[{"type":"text","text":"Set one or more user field values on the current user."},{"type":"text","text":" "},{"type":"text","text":"To see the fields available for setting use the get"},{"text":" ","type":"text"},{"text":"User method and inspect the user fields dictionary.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendeskcoresdk\/zdkuserprovider\/setuserfields(_:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendeskcoresdk\/zdkuserprovider\/setuserfields(_:completion:)"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"title":"ZendeskCoreSDK","url":"\/documentation\/zendeskcoresdk","type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","abstract":[]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKUserProvider/setUserFields(_:completion:)":{"title":"setUserFields(_:completion:)","type":"topic","abstract":[{"text":"Set one or more user field values on the current user.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"To see the fields available for setting use the get"},{"text":" ","type":"text"},{"text":"User method and inspect the user fields dictionary.","type":"text"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKUserProvider\/setUserFields(_:completion:)","role":"symbol","url":"\/documentation\/zendeskcoresdk\/zdkuserprovider\/setuserfields(_:completion:)","navigatorTitle":[{"kind":"identifier","text":"setUserFields:completion:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setUserFields","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"], "},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUser","text":"User"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":"))","kind":"text"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKUserProvider":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKUserProvider","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKUserProvider","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKUserProvider","title":"ZDKUserProvider","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk\/zdkuserprovider","abstract":[{"text":"An objective-c visible class for the User Provider","type":"text"}],"role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/User":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"User","kind":"identifier"}],"navigatorTitle":[{"text":"User","kind":"identifier"}],"abstract":[{"text":"A user in Zendesk.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User","url":"\/documentation\/zendeskcoresdk\/user","title":"User"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"setUserFields:completion:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"setUserFields:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"setUserFields:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,id>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userFields"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv(#*$@M@ZendeskCoreSDK@objc(cs)ZDKClassicUser#*$objc(cs)NSError)","text":"void (^)(ZDKClassicUser *, NSError *)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKUserProvider~1setUserFields(_:completion:)\/title","op":"replace","value":"setUserFields:completion:"},{"value":[{"kind":"text","text":"- "},{"text":"setUserFields:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKUserProvider~1setUserFields(_:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKUserProvider\/title","value":"ZDKClassicUserProvider"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKUserProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKClassicUserProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User\/title","value":"ZDKClassicUser"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User\/fragments","op":"replace","value":[{"text":"ZDKClassicUser","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}