{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"bool indicating if user field is active"}],"variants":[{"paths":["\/documentation\/zendeskcoresdk\/userfield\/active"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendeskcoresdk\/userfield\/active"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"active","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserField\/active"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserField"]]},"metadata":{"modules":[{"name":"ZendeskCoreSDK"}],"externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUserField(py)active","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"active","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","title":"active","symbolKind":"property","navigatorTitle":[{"text":"active","kind":"identifier"}]},"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/UserField":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserField","kind":"identifier"}],"abstract":[{"type":"text","text":"User Field in Zendesk"}],"title":"UserField","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserField","url":"\/documentation\/zendeskcoresdk\/userfield","kind":"symbol","type":"topic","navigatorTitle":[{"text":"UserField","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/UserField/active":{"navigatorTitle":[{"kind":"identifier","text":"active"}],"url":"\/documentation\/zendeskcoresdk\/userfield\/active","role":"symbol","title":"active","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserField\/active","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"active","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"type":"text","text":"bool indicating if user field is active"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"type":"topic","role":"collection","title":"ZendeskCoreSDK","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","abstract":[],"kind":"symbol","url":"\/documentation\/zendeskcoresdk"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"active","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"active"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"active","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKClassicUserField","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserField\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserField\/fragments","value":[{"kind":"identifier","text":"ZDKClassicUserField"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserField~1active\/title","value":"active","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserField~1active\/fragments","value":[{"text":"active","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}