{"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/CoreLogger","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/PushRegistrationProvider","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Stores","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserField","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserFieldOption","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKIdentityMigrator","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCAnonymous","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCJwt","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKUserProvider","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk"],"title":"Classes"},{"title":"Protocols","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/AccessStatusProvider","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/AccountDetails","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ActionHandler","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/CachedHTTPURLResponseDelegate","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/CachedHTTPURLResponseDetails","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/CachedHTTPURLResponseTransformer","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ClientHeaders","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/DecodableDefault","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Executor","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityMigration","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LoggerType","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ProviderModule","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/StoreModule","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/URLProvider","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/URLService","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCIdentity"]},{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ActionDescription","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ActionHandlerRegistry","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Anonymous","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ApplicationConfiguration","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/BaseStore","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/BlipsProvider","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/CoreSettings","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Jwt","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/NilAction","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/PageView","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ProviderService","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/PushRegistrationResponse","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/SDKError","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/SessionStore","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/SettingsProvider","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/SharedHeaders","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserAction","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserProvider"],"title":"Structures"},{"title":"Type Aliases","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ActionInfo","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/CompletionHandler","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ProgressCallback","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/PushRegistrationResult"]},{"title":"Enumerations","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/AccessStatus","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/BlipsGroup","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ConsoleLogger","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HttpMethod","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Identity","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LoggerConfig","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Reporter","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Settings"]},{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Foundation"],"title":"Extended Modules"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/zendeskcoresdk"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendeskcoresdk"]}],"sections":[],"hierarchy":{"paths":[[]]},"metadata":{"modules":[{"name":"ZendeskCoreSDK"}],"role":"collection","title":"ZendeskCoreSDK","symbolKind":"module","externalID":"ZendeskCoreSDK","roleHeading":"Framework"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/AccessStatus":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AccessStatus","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/AccessStatus","abstract":[],"type":"topic","title":"AccessStatus","navigatorTitle":[{"kind":"identifier","text":"AccessStatus"}],"url":"\/documentation\/zendeskcoresdk\/accessstatus","kind":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/PushRegistrationResponse":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PushRegistrationResponse"}],"navigatorTitle":[{"text":"PushRegistrationResponse","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/PushRegistrationResponse","title":"PushRegistrationResponse","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk\/pushregistrationresponse","abstract":[],"role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/SharedHeaders":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharedHeaders"}],"navigatorTitle":[{"text":"SharedHeaders","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/SharedHeaders","title":"SharedHeaders","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk\/sharedheaders","abstract":[],"role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"title":"ZendeskCoreSDK","url":"\/documentation\/zendeskcoresdk","type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","abstract":[]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/UserFieldOption":{"url":"\/documentation\/zendeskcoresdk\/userfieldoption","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserFieldOption","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserFieldOption","navigatorTitle":[{"text":"UserFieldOption","kind":"identifier"}],"kind":"symbol","title":"UserFieldOption","abstract":[{"text":"Dropdown userfields can contain User fields options which describe an option in the","type":"text"},{"type":"text","text":" "},{"text":"dropdown","type":"text"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ProviderModule":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProviderModule"}],"navigatorTitle":[{"text":"ProviderModule","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ProviderModule","title":"ProviderModule","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk\/providermodule","abstract":[],"role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Reporter":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Reporter"}],"navigatorTitle":[{"text":"Reporter","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Reporter","title":"Reporter","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk\/reporter","abstract":[],"role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKUserProvider":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ZDKUserProvider","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKUserProvider","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKUserProvider","title":"ZDKUserProvider","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk\/zdkuserprovider","abstract":[{"text":"An objective-c visible class for the User Provider","type":"text"}],"role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ConsoleLogger":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConsoleLogger","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ConsoleLogger"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ConsoleLogger","title":"ConsoleLogger","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk\/consolelogger","abstract":[],"role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/User":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"User","kind":"identifier"}],"navigatorTitle":[{"text":"User","kind":"identifier"}],"abstract":[{"text":"A user in Zendesk.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User","url":"\/documentation\/zendeskcoresdk\/user","title":"User"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/SettingsProvider":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SettingsProvider","kind":"identifier"}],"navigatorTitle":[{"text":"SettingsProvider","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/SettingsProvider","title":"SettingsProvider","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk\/settingsprovider","abstract":[],"role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Anonymous":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Anonymous","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Anonymous"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Anonymous","title":"Anonymous","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk\/anonymous","abstract":[],"role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/PageView":{"navigatorTitle":[{"text":"PageView","kind":"identifier"}],"abstract":[{"type":"text","text":"Public model used to allow consumers to send PageView Blip data"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/PageView","type":"topic","url":"\/documentation\/zendeskcoresdk\/pageview","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PageView"}],"title":"PageView","kind":"symbol","role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/LogLevel":{"title":"LogLevel","url":"\/documentation\/zendeskcoresdk\/loglevel","type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LogLevel"}],"navigatorTitle":[{"kind":"identifier","text":"LogLevel"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/StoreModule":{"kind":"symbol","title":"StoreModule","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/StoreModule","role":"symbol","navigatorTitle":[{"text":"StoreModule","kind":"identifier"}],"url":"\/documentation\/zendeskcoresdk\/storemodule","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"StoreModule"}],"abstract":[]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ActionHandlerRegistry":{"title":"ActionHandlerRegistry","url":"\/documentation\/zendeskcoresdk\/actionhandlerregistry","kind":"symbol","abstract":[{"text":"A registry of objects to be used for inter-SDK actions, such as starting","type":"text"},{"text":" ","type":"text"},{"text":"a view controller from one SDK, in another SDK, without","type":"text"},{"type":"text","text":" "},{"text":"any dependency between them.","type":"text"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionHandlerRegistry","kind":"identifier"}],"navigatorTitle":[{"text":"ActionHandlerRegistry","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ActionHandlerRegistry","type":"topic"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/IdentityType":{"kind":"symbol","url":"\/documentation\/zendeskcoresdk\/identitytype","role":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType","navigatorTitle":[{"text":"IdentityType","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IdentityType"}],"title":"IdentityType"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/UserAction":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserAction","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"UserAction"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserAction","title":"UserAction","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk\/useraction","abstract":[{"type":"text","text":"Public model used to allow consumers to send UserAction Blip data"}],"role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/SDKError":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SDKError","kind":"identifier"}],"navigatorTitle":[{"text":"SDKError","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/SDKError","title":"SDKError","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk\/sdkerror","abstract":[],"role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ProgressCallback":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProgressCallback"}],"navigatorTitle":[{"kind":"identifier","text":"ProgressCallback"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ProgressCallback","title":"ProgressCallback","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk\/progresscallback","abstract":[],"role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKObjCAnonymous":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCAnonymous","abstract":[],"url":"\/documentation\/zendeskcoresdk\/zdkobjcanonymous","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKObjCAnonymous","kind":"identifier"}],"title":"ZDKObjCAnonymous","kind":"symbol","navigatorTitle":[{"text":"ZDKObjCAnonymous","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/CachedHTTPURLResponseTransformer":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/CachedHTTPURLResponseTransformer","abstract":[],"url":"\/documentation\/zendeskcoresdk\/cachedhttpurlresponsetransformer","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CachedHTTPURLResponseTransformer","kind":"identifier"}],"title":"CachedHTTPURLResponseTransformer","kind":"symbol","navigatorTitle":[{"text":"CachedHTTPURLResponseTransformer","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/HttpMethod":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HttpMethod","abstract":[],"url":"\/documentation\/zendeskcoresdk\/httpmethod","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HttpMethod","kind":"identifier"}],"title":"HttpMethod","kind":"symbol","navigatorTitle":[{"text":"HttpMethod","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Foundation":{"url":"\/documentation\/zendeskcoresdk\/foundation","type":"topic","title":"Foundation","kind":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Foundation","abstract":[],"role":"collection"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/BaseStore":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BaseStore"}],"navigatorTitle":[{"kind":"identifier","text":"BaseStore"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/BaseStore","kind":"symbol","url":"\/documentation\/zendeskcoresdk\/basestore","abstract":[{"text":"Storage for values that live for a device install.","type":"text"}],"role":"symbol","title":"BaseStore"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/AccessStatusProvider":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/AccessStatusProvider","abstract":[],"url":"\/documentation\/zendeskcoresdk\/accessstatusprovider","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccessStatusProvider","kind":"identifier"}],"title":"AccessStatusProvider","kind":"symbol","navigatorTitle":[{"text":"AccessStatusProvider","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/CachedHTTPURLResponseDetails":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CachedHTTPURLResponseDetails","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/CachedHTTPURLResponseDetails","abstract":[],"type":"topic","title":"CachedHTTPURLResponseDetails","navigatorTitle":[{"text":"CachedHTTPURLResponseDetails","kind":"identifier"}],"url":"\/documentation\/zendeskcoresdk\/cachedhttpurlresponsedetails","kind":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/BlipsGroup":{"role":"symbol","title":"BlipsGroup","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BlipsGroup"}],"url":"\/documentation\/zendeskcoresdk\/blipsgroup","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/BlipsGroup","navigatorTitle":[{"text":"BlipsGroup","kind":"identifier"}],"abstract":[]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/PushRegistrationProvider":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/PushRegistrationProvider","kind":"symbol","title":"PushRegistrationProvider","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PushRegistrationProvider","kind":"identifier"}],"navigatorTitle":[{"text":"PushRegistrationProvider","kind":"identifier"}],"url":"\/documentation\/zendeskcoresdk\/pushregistrationprovider"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Jwt":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Jwt","abstract":[],"url":"\/documentation\/zendeskcoresdk\/jwt","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Jwt","kind":"identifier"}],"title":"Jwt","kind":"symbol","navigatorTitle":[{"text":"Jwt","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZendeskCoreSDK_h":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZendeskCoreSDK_h","abstract":[],"url":"\/documentation\/zendeskcoresdk\/zendeskcoresdk_h","type":"topic","role":"symbol","fragments":[{"text":"ZendeskCoreSDK_h","kind":"identifier"}],"title":"ZendeskCoreSDK_h","kind":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Settings":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Settings","abstract":[],"url":"\/documentation\/zendeskcoresdk\/settings","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Settings","kind":"identifier"}],"title":"Settings","kind":"symbol","navigatorTitle":[{"text":"Settings","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKPushProvider":{"title":"ZDKPushProvider","type":"topic","role":"symbol","abstract":[{"type":"text","text":"An objective-c visible class for the Push Registration Provider"},{"type":"text","text":" "},{"type":"text","text":"Provider to register and unregister a device for push notifications."}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKPushProvider"}],"url":"\/documentation\/zendeskcoresdk\/zdkpushprovider","navigatorTitle":[{"text":"ZDKPushProvider","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/PushRegistrationResult":{"abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/PushRegistrationResult","type":"topic","title":"PushRegistrationResult","kind":"symbol","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PushRegistrationResult"}],"navigatorTitle":[{"kind":"identifier","text":"PushRegistrationResult"}],"url":"\/documentation\/zendeskcoresdk\/pushregistrationresult"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/UserField":{"kind":"symbol","type":"topic","abstract":[{"text":"User Field in Zendesk","type":"text"}],"title":"UserField","role":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserField","url":"\/documentation\/zendeskcoresdk\/userfield","navigatorTitle":[{"text":"UserField","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserField"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/CompletionHandler":{"url":"\/documentation\/zendeskcoresdk\/completionhandler","abstract":[{"text":"Type alias for a network completion handler.","type":"text"}],"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CompletionHandler","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/CompletionHandler","title":"CompletionHandler","navigatorTitle":[{"text":"CompletionHandler","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ProviderService":{"title":"ProviderService","type":"topic","role":"symbol","url":"\/documentation\/zendeskcoresdk\/providerservice","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProviderService"}],"navigatorTitle":[{"kind":"identifier","text":"ProviderService"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ProviderService","abstract":[]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/DecodableDefault":{"url":"\/documentation\/zendeskcoresdk\/decodabledefault","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DecodableDefault","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/DecodableDefault","title":"DecodableDefault","navigatorTitle":[{"text":"DecodableDefault","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ActionHandler":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ActionHandler","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ActionHandler","title":"ActionHandler","navigatorTitle":[{"text":"ActionHandler","kind":"identifier"}],"abstract":[{"text":"Defines a handler for an inter-SDK action, such as one SDK starting another one, without either","type":"text"},{"type":"text","text":" "},{"text":"SDK having a dependency on the other. An example of this would be a hypothetical Help Center","type":"text"},{"text":" ","type":"text"},{"text":"SDK starting the “create ticket” screen of the Support SDK.","type":"text"},{"type":"text","text":" "},{"text":"In order to properly separate SDKs from each other, handlers will work on “action Strings”.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Multiple SDKs can be capable of handling the same action"},{"text":" ","type":"text"},{"text":"String. For example, a “contact us” action can be handled by Support, Chat, Voice, Message, etc.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"In the event that more than one ActionHandler has been registered for the same actionString,"},{"text":" ","type":"text"},{"type":"text","text":"the priority variable can be used to determine which one to call the handle method on."}],"url":"\/documentation\/zendeskcoresdk\/actionhandler","kind":"symbol","role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/BlipsProvider":{"role":"symbol","title":"BlipsProvider","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"BlipsProvider","kind":"identifier"}],"url":"\/documentation\/zendeskcoresdk\/blipsprovider","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/BlipsProvider","navigatorTitle":[{"kind":"identifier","text":"BlipsProvider"}],"abstract":[]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/NilAction":{"url":"\/documentation\/zendeskcoresdk\/nilaction","abstract":[],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NilAction","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/NilAction","title":"NilAction","navigatorTitle":[{"text":"NilAction","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ActionInfo":{"url":"\/documentation\/zendeskcoresdk\/actioninfo","abstract":[],"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionInfo","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ActionInfo","title":"ActionInfo","navigatorTitle":[{"text":"ActionInfo","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKIdentityMigrator":{"url":"\/documentation\/zendeskcoresdk\/zdkidentitymigrator","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKIdentityMigrator","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKIdentityMigrator","title":"ZDKIdentityMigrator","navigatorTitle":[{"text":"ZDKIdentityMigrator","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKObjCIdentity":{"url":"\/documentation\/zendeskcoresdk\/zdkobjcidentity","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKObjCIdentity","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCIdentity","title":"ZDKObjCIdentity","navigatorTitle":[{"text":"ZDKObjCIdentity","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/CoreLogger":{"url":"\/documentation\/zendeskcoresdk\/corelogger","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CoreLogger","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/CoreLogger","title":"CoreLogger","navigatorTitle":[{"text":"CoreLogger","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/UserProvider":{"role":"symbol","abstract":[{"text":"Provides an API to interact with a zendesk user object","type":"text"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserProvider","title":"UserProvider","url":"\/documentation\/zendeskcoresdk\/userprovider","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserProvider"}],"navigatorTitle":[{"kind":"identifier","text":"UserProvider"}],"kind":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/LoggerType":{"url":"\/documentation\/zendeskcoresdk\/loggertype","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerType","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LoggerType","title":"LoggerType","navigatorTitle":[{"text":"LoggerType","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/IdentityMigration":{"url":"\/documentation\/zendeskcoresdk\/identitymigration","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IdentityMigration","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityMigration","title":"IdentityMigration","navigatorTitle":[{"text":"IdentityMigration","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Zendesk":{"type":"topic","title":"Zendesk","url":"\/documentation\/zendeskcoresdk\/zendesk","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Zendesk"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Zendesk"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk","role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/CachedHTTPURLResponseDelegate":{"url":"\/documentation\/zendeskcoresdk\/cachedhttpurlresponsedelegate","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CachedHTTPURLResponseDelegate","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/CachedHTTPURLResponseDelegate","title":"CachedHTTPURLResponseDelegate","navigatorTitle":[{"text":"CachedHTTPURLResponseDelegate","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/CoreSettings":{"abstract":[],"role":"symbol","type":"topic","title":"CoreSettings","kind":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/CoreSettings","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CoreSettings"}],"navigatorTitle":[{"text":"CoreSettings","kind":"identifier"}],"url":"\/documentation\/zendeskcoresdk\/coresettings"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/URLProvider":{"url":"\/documentation\/zendeskcoresdk\/urlprovider","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"URLProvider","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/URLProvider","title":"URLProvider","navigatorTitle":[{"text":"URLProvider","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKObjCJwt":{"url":"\/documentation\/zendeskcoresdk\/zdkobjcjwt","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKObjCJwt","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCJwt","title":"ZDKObjCJwt","navigatorTitle":[{"text":"ZDKObjCJwt","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Identity":{"title":"Identity","url":"\/documentation\/zendeskcoresdk\/identity","role":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Identity","navigatorTitle":[{"text":"Identity","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Identity"}],"kind":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/AccountDetails":{"title":"AccountDetails","type":"topic","role":"symbol","url":"\/documentation\/zendeskcoresdk\/accountdetails","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AccountDetails"}],"navigatorTitle":[{"kind":"identifier","text":"AccountDetails"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/AccountDetails","abstract":[]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Stores":{"url":"\/documentation\/zendeskcoresdk\/stores","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Stores","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Stores","title":"Stores","navigatorTitle":[{"text":"Stores","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ActionDescription":{"title":"ActionDescription","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"An object which describes an "},{"type":"codeVoice","code":"ActionHandler"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ActionDescription","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionDescription","kind":"identifier"}],"url":"\/documentation\/zendeskcoresdk\/actiondescription","navigatorTitle":[{"text":"ActionDescription","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ClientHeaders":{"url":"\/documentation\/zendeskcoresdk\/clientheaders","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClientHeaders","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ClientHeaders","title":"ClientHeaders","navigatorTitle":[{"text":"ClientHeaders","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ApplicationConfiguration":{"url":"\/documentation\/zendeskcoresdk\/applicationconfiguration","abstract":[{"text":"The Zendesk Application information","type":"text"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ApplicationConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ApplicationConfiguration","title":"ApplicationConfiguration","navigatorTitle":[{"text":"ApplicationConfiguration","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/SessionStore":{"url":"\/documentation\/zendeskcoresdk\/sessionstore","kind":"symbol","abstract":[{"text":"Store the application session to user deaults","type":"text"}],"title":"SessionStore","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SessionStore"}],"navigatorTitle":[{"text":"SessionStore","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/SessionStore","type":"topic"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/HelpCenterUtil":{"title":"HelpCenterUtil","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HelpCenterUtil"}],"url":"\/documentation\/zendeskcoresdk\/helpcenterutil","kind":"symbol","type":"topic","abstract":[{"text":"Utility to add auth headers to content requests for restricted Help Centers","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"HelpCenterUtil","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/LoggerConfig":{"url":"\/documentation\/zendeskcoresdk\/loggerconfig","abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerConfig","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LoggerConfig","title":"LoggerConfig","navigatorTitle":[{"text":"LoggerConfig","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/URLService":{"url":"\/documentation\/zendeskcoresdk\/urlservice","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"URLService","kind":"identifier"}],"title":"URLService","type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/URLService","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"URLService"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Executor":{"url":"\/documentation\/zendeskcoresdk\/executor","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Executor","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Executor","title":"Executor","navigatorTitle":[{"text":"Executor","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":[{"title":"Classes","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/CoreLogger","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserField","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserFieldOption","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKIdentityMigrator","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCAnonymous","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCJwt","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKUserProvider","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk"]},{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityMigration","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCIdentity"],"title":"Protocols"},{"title":"Macros","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZendeskCoreSDK_h"]},{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel"],"title":"Enumerations"}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":"ZDKClassicUserFieldOption","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserFieldOption\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserFieldOption\/fragments","value":[{"kind":"identifier","text":"ZDKClassicUserFieldOption"}],"op":"replace"},{"value":"ZDKClassicUserProvider","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKUserProvider\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKUserProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKClassicUserProvider"}]},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User\/title","value":"ZDKClassicUser","op":"replace"},{"op":"replace","value":[{"text":"ZDKClassicUser","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel\/title","value":"ZDKClassicLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel\/fragments","value":[{"kind":"identifier","text":"ZDKClassicLogLevel"}]},{"value":"ZDKClassicIdentityType","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityType\/title","op":"replace"},{"value":[{"text":"ZDKClassicIdentityType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityType\/fragments","op":"replace"},{"op":"replace","value":"ZDKObjCAnonymous","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCAnonymous\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCAnonymous\/fragments","value":[{"kind":"identifier","text":"ZDKObjCAnonymous"}]},{"value":"ZDKClassicPushProvider","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKPushProvider\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKPushProvider\/fragments","op":"replace","value":[{"text":"ZDKClassicPushProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserField\/title","value":"ZDKClassicUserField"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserField\/fragments","value":[{"kind":"identifier","text":"ZDKClassicUserField"}]},{"value":"ZDKIdentityMigrator","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKIdentityMigrator\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKIdentityMigrator\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKIdentityMigrator"}]},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCIdentity\/title","value":"ZDKObjCIdentity","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCIdentity\/fragments","value":[{"text":"ZDKObjCIdentity","kind":"identifier"}],"op":"replace"},{"value":"ZDKClassicCoreLogger","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1CoreLogger\/title"},{"value":[{"kind":"identifier","text":"ZDKClassicCoreLogger"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1CoreLogger\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityMigration\/title","value":"IdentityMigration"},{"value":[{"kind":"identifier","text":"IdentityMigration"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityMigration\/fragments"},{"op":"replace","value":"ZDKClassicZendesk","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKClassicZendesk"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk\/fragments"},{"value":"ZDKObjCJwt","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCJwt\/title"},{"value":[{"kind":"identifier","text":"ZDKObjCJwt"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCJwt\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1HelpCenterUtil\/title","value":"ZDKClassicHelpCenterUtil","op":"replace"},{"op":"replace","value":[{"text":"ZDKClassicHelpCenterUtil","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1HelpCenterUtil\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}