{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jwt"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/zendeskcoresdk\/identitytype\/jwt"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendeskcoresdk\/identitytype\/jwt"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType\/jwt","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jwt"}],"title":"IdentityType.jwt","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@ZendeskCoreSDK@E@ZDKClassicIdentityType@ZDKClassicIdentityTypeJwt","modules":[{"name":"ZendeskCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKClassicIdentityTypeJwt"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType"]]},"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/IdentityType":{"role":"symbol","title":"IdentityType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdentityType"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IdentityType"}],"url":"\/documentation\/zendeskcoresdk\/identitytype"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/IdentityType/jwt":{"role":"symbol","title":"IdentityType.jwt","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jwt"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType\/jwt","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKClassicIdentityTypeJwt"}],"url":"\/documentation\/zendeskcoresdk\/identitytype\/jwt"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"role":"collection","title":"ZendeskCoreSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKClassicIdentityTypeJwt"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ZDKClassicIdentityTypeJwt"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ZDKClassicIdentityTypeJwt"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityType\/title","value":"ZDKClassicIdentityType"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityType\/fragments","value":[{"kind":"identifier","text":"ZDKClassicIdentityType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityType~1jwt\/title","value":"ZDKClassicIdentityTypeJwt"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityType~1jwt\/fragments","value":[{"kind":"identifier","text":"ZDKClassicIdentityTypeJwt"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}