{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"objCIdentity"}],"extendedModule":"ZendeskCoreSDK","roleHeading":"Instance Method","title":"objCIdentity()","externalID":"c:@CM@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk(im)objCIdentity","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"objCIdentity","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"ZDKObjCIdentity","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(pl)ZDKObjCIdentity"},{"kind":"text","text":"?"}],"modules":[{"name":"ZendeskCoreSDK"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/objCIdentity()"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/zendeskcoresdk\/zendesk\/objcidentity()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendeskcoresdk\/zendesk\/objcidentity()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"objCIdentity","kind":"identifier"},{"text":"() -> ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCIdentity","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(pl)ZDKObjCIdentity","text":"ZDKObjCIdentity"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKObjCIdentity":{"url":"\/documentation\/zendeskcoresdk\/zdkobjcidentity","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKObjCIdentity","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCIdentity","title":"ZDKObjCIdentity","navigatorTitle":[{"text":"ZDKObjCIdentity","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"title":"ZendeskCoreSDK","url":"\/documentation\/zendeskcoresdk","type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","abstract":[]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Zendesk/objCIdentity()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"objCIdentity","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"ZDKObjCIdentity","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(pl)ZDKObjCIdentity"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"objCIdentity","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk\/objCIdentity()","title":"objCIdentity()","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk\/zendesk\/objcidentity()","abstract":[],"role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/Zendesk":{"type":"topic","title":"Zendesk","url":"\/documentation\/zendeskcoresdk\/zendesk","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Zendesk"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Zendesk"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/Zendesk","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"objCIdentity","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"objCIdentity","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:Qo@M@ZendeskCoreSDK@objc(pl)ZDKObjCIdentity","text":"id<ZDKObjCIdentity>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"objCIdentity","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCIdentity\/title","value":"ZDKObjCIdentity"},{"value":[{"kind":"identifier","text":"ZDKObjCIdentity"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCIdentity\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk~1objCIdentity()\/title","value":"objCIdentity"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk~1objCIdentity()\/fragments","value":[{"kind":"text","text":"- "},{"text":"objCIdentity","kind":"identifier"}],"op":"replace"},{"value":"ZDKClassicZendesk","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk\/title"},{"value":[{"text":"ZDKClassicZendesk","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1Zendesk\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}