{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"The timestamp of when the field was created","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"created_at","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Date","preciseIdentifier":"s:10Foundation4DateV"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendeskcoresdk\/userfield\/created_at"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendeskcoresdk\/userfield\/created_at"]}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"created_at","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"created_at","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DateV","kind":"typeIdentifier","text":"Date"}],"navigatorTitle":[{"kind":"identifier","text":"created_at"}],"modules":[{"name":"ZendeskCoreSDK"}],"externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUserField(py)created_at"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserField"]]},"identifier":{"url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserField\/created_at","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/UserField/created_at":{"url":"\/documentation\/zendeskcoresdk\/userfield\/created_at","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"created_at"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"abstract":[{"type":"text","text":"The timestamp of when the field was created"}],"type":"topic","title":"created_at","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserField\/created_at","navigatorTitle":[{"kind":"identifier","text":"created_at"}],"role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/UserField":{"title":"UserField","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserField","abstract":[{"text":"User Field in Zendesk","type":"text"}],"navigatorTitle":[{"text":"UserField","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/zendeskcoresdk\/userfield","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserField"}],"type":"topic"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","role":"collection","url":"\/documentation\/zendeskcoresdk","kind":"symbol","abstract":[],"title":"ZendeskCoreSDK"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"created_at"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"created_at","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDate","text":"NSDate"},{"kind":"text","text":" * "},{"kind":"identifier","text":"created_at"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserField~1created_at\/title","op":"replace","value":"created_at"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserField~1created_at\/fragments","value":[{"text":"created_at","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserField\/title","value":"ZDKClassicUserField","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKClassicUserField"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserField\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}