{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKClassicHelpCenterUtil) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HelpCenterUtil"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Utility to add auth headers to content requests for restricted Help Centers"}],"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil\/hasAuth","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil\/zendeskURL"]},{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil\/canonicalRequest(for:)"],"title":"Type Methods"}],"variants":[{"paths":["\/documentation\/zendeskcoresdk\/helpcenterutil"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendeskcoresdk\/helpcenterutil"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicHelpCenterUtil","symbolKind":"class","title":"HelpCenterUtil","navigatorTitle":[{"text":"HelpCenterUtil","kind":"identifier"}],"modules":[{"name":"ZendeskCoreSDK"}],"role":"symbol","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HelpCenterUtil","kind":"identifier"}]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.ZendeskCoreSDK\/s7CVarArgP","doc:\/\/com.zendesk.ZendeskCoreSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.ZendeskCoreSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.ZendeskCoreSDK\/SQ","doc:\/\/com.zendesk.ZendeskCoreSDK\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"references":{"doc://com.zendesk.ZendeskCoreSDK/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/HelpCenterUtil/hasAuth":{"abstract":[],"title":"hasAuth","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"hasAuth"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil\/hasAuth","url":"\/documentation\/zendeskcoresdk\/helpcenterutil\/hasauth","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasAuth"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.zendesk.ZendeskCoreSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(cs)NSObject"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKClassicHelpCenterUtil/init":{"url":"\/documentation\/zendeskcoresdk\/zdkclassichelpcenterutil\/init","navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKClassicHelpCenterUtil\/init","kind":"symbol","title":"init","role":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/HelpCenterUtil/zendeskURL":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"zendeskURL","kind":"identifier"}],"abstract":[],"title":"zendeskURL","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil\/zendeskURL","type":"topic","url":"\/documentation\/zendeskcoresdk\/helpcenterutil\/zendeskurl","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"zendeskURL","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.zendesk.ZendeskCoreSDK/SH":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.ZendeskCoreSDK/SQ":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"type":"topic","role":"collection","title":"ZendeskCoreSDK","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","abstract":[],"kind":"symbol","url":"\/documentation\/zendeskcoresdk"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/HelpCenterUtil/canonicalRequest(for:)":{"url":"\/documentation\/zendeskcoresdk\/helpcenterutil\/canonicalrequest(for:)","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"canonicalRequestFor:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canonicalRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSURLRequest","preciseIdentifier":"c:objc(cs)NSURLRequest","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLRequest","text":"NSURLRequest","kind":"typeIdentifier"}],"title":"canonicalRequest(for:)","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil\/canonicalRequest(for:)","abstract":[]},"doc://com.zendesk.ZendeskCoreSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.zendesk.ZendeskCoreSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/HelpCenterUtil":{"kind":"symbol","abstract":[{"type":"text","text":"Utility to add auth headers to content requests for restricted Help Centers"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"HelpCenterUtil","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HelpCenterUtil","kind":"identifier"}],"title":"HelpCenterUtil","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil","url":"\/documentation\/zendeskcoresdk\/helpcenterutil"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"ZDKClassicHelpCenterUtil","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKClassicHelpCenterUtil"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKClassicHelpCenterUtil"}]},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKClassicHelpCenterUtil\/init"]},{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil\/hasAuth","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil\/zendeskURL"],"title":"Type Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/HelpCenterUtil\/canonicalRequest(for:)"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"ZDKClassicHelpCenterUtil","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1HelpCenterUtil~1hasAuth\/title","value":"hasAuth","op":"replace"},{"value":[{"text":"hasAuth","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1HelpCenterUtil~1hasAuth\/fragments","op":"replace"},{"value":"zendeskURL","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1HelpCenterUtil~1zendeskURL\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1HelpCenterUtil~1zendeskURL\/fragments","op":"replace","value":[{"kind":"identifier","text":"zendeskURL"}]},{"op":"replace","value":"canonicalRequestFor:","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1HelpCenterUtil~1canonicalRequest(for:)\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1HelpCenterUtil~1canonicalRequest(for:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"canonicalRequestFor:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1HelpCenterUtil\/title","value":"ZDKClassicHelpCenterUtil"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1HelpCenterUtil\/fragments","value":[{"text":"ZDKClassicHelpCenterUtil","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}