{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Calls a push registration end point to register the given Urban Airship channel id.","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"register","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UAIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"locale"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method stores the response on successful registration."},{"text":" ","type":"text"},{"text":"Subsequent calls to this method with the same ","type":"text"},{"type":"codeVoice","code":"identifier"},{"type":"text","text":" bypass calls to the"},{"type":"text","text":" "},{"text":"network and return the stored response in the completion handler.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Calling this method with a different "},{"code":"identifier","type":"codeVoice"},{"text":" will remove any stored","type":"text"},{"type":"text","text":" "},{"text":"response from storage.","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"UAIdentifier: The channel identifier","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"locale: The preferred device locale"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"completion: Returns a push response if successful with a nil for the error","type":"text"}]}]}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendeskcoresdk\/zdkpushprovider\/register(uaidentifier:locale:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendeskcoresdk\/zdkpushprovider\/register(uaidentifier:locale:completion:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider\/register(UAIdentifier:locale:completion:)"},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"registerWithUAIdentifier:locale:completion:","kind":"identifier"}],"externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicPushProvider(im)registerWithUAIdentifier:locale:completion:","title":"register(UAIdentifier:locale:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"register"},{"text":"(","kind":"text"},{"text":"UAIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"locale"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"role":"symbol","modules":[{"name":"ZendeskCoreSDK"}],"roleHeading":"Instance Method","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider"]]},"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKPushProvider/register(UAIdentifier:locale:completion:)":{"type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider\/register(UAIdentifier:locale:completion:)","url":"\/documentation\/zendeskcoresdk\/zdkpushprovider\/register(uaidentifier:locale:completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"registerWithUAIdentifier:locale:completion:"}],"title":"register(UAIdentifier:locale:completion:)","kind":"symbol","abstract":[{"type":"text","text":"Calls a push registration end point to register the given Urban Airship channel id."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"register","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UAIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"locale"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKPushProvider":{"type":"topic","role":"symbol","title":"ZDKPushProvider","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKPushProvider"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider","kind":"symbol","abstract":[{"type":"text","text":"An objective-c visible class for the Push Registration Provider"},{"text":" ","type":"text"},{"text":"Provider to register and unregister a device for push notifications.","type":"text"}],"url":"\/documentation\/zendeskcoresdk\/zdkpushprovider","navigatorTitle":[{"kind":"identifier","text":"ZDKPushProvider"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","kind":"symbol","url":"\/documentation\/zendeskcoresdk","abstract":[],"title":"ZendeskCoreSDK"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"registerWithUAIdentifier:locale:completion:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"registerWithUAIdentifier:locale:completion:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"registerWithUAIdentifier:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"UAIdentifier"},{"kind":"text","text":" "},{"text":"locale:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"locale","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)NSString#*$objc(cs)NSError)","text":"void (^)(NSString *, NSError *)"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKPushProvider~1register(UAIdentifier:locale:completion:)\/title","value":"registerWithUAIdentifier:locale:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKPushProvider~1register(UAIdentifier:locale:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"registerWithUAIdentifier:locale:completion:"}],"op":"replace"},{"op":"replace","value":"ZDKClassicPushProvider","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKPushProvider\/title"},{"value":[{"kind":"identifier","text":"ZDKClassicPushProvider"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKPushProvider\/fragments"}]}]}