{"topicSections":[{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCIdentity\/type"],"title":"Instance Properties"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK"]]},"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKObjCIdentity"}],"title":"ZDKObjCIdentity","symbolKind":"protocol","externalID":"c:@M@ZendeskCoreSDK@objc(pl)ZDKObjCIdentity","role":"symbol","navigatorTitle":[{"text":"ZDKObjCIdentity","kind":"identifier"}],"modules":[{"name":"ZendeskCoreSDK"}],"roleHeading":"Protocol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKObjCIdentity"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCIdentity","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendeskcoresdk\/zdkobjcidentity"]},{"paths":["\/documentation\/zendeskcoresdk\/zdkobjcidentity"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCAnonymous","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCJwt"],"kind":"relationships","type":"conformingTypes","title":"Conforming Types"}],"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKObjCJwt":{"type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCJwt","role":"symbol","url":"\/documentation\/zendeskcoresdk\/zdkobjcjwt","title":"ZDKObjCJwt","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKObjCJwt"}],"navigatorTitle":[{"text":"ZDKObjCJwt","kind":"identifier"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKObjCIdentity/type":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IdentityType","preciseIdentifier":"c:@M@ZendeskCoreSDK@E@ZDKClassicIdentityType","kind":"typeIdentifier"}],"kind":"symbol","title":"type","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCIdentity\/type","url":"\/documentation\/zendeskcoresdk\/zdkobjcidentity\/type","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"type"}],"role":"symbol","required":true},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKObjCAnonymous":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKObjCAnonymous","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCAnonymous","title":"ZDKObjCAnonymous","url":"\/documentation\/zendeskcoresdk\/zdkobjcanonymous","abstract":[],"navigatorTitle":[{"text":"ZDKObjCAnonymous","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","role":"collection","url":"\/documentation\/zendeskcoresdk","kind":"symbol","abstract":[],"title":"ZendeskCoreSDK"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKObjCIdentity":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKObjCIdentity","kind":"identifier"}],"kind":"symbol","title":"ZDKObjCIdentity","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCIdentity","url":"\/documentation\/zendeskcoresdk\/zdkobjcidentity","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ZDKObjCIdentity"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"ZDKObjCIdentity"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"value":[{"kind":"identifier","text":"ZDKObjCIdentity"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKObjCIdentity"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCIdentity\/type"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Conforming Types","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCAnonymous","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCJwt"],"type":"conformingTypes","kind":"relationships"}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKObjCIdentity"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCJwt\/title","op":"replace","value":"ZDKObjCJwt"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCJwt\/fragments","value":[{"kind":"identifier","text":"ZDKObjCJwt"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCIdentity~1type\/title","op":"replace","value":"type"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCIdentity~1type\/fragments","value":[{"text":"type","kind":"identifier"}]},{"op":"replace","value":"ZDKObjCAnonymous","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCAnonymous\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCAnonymous\/fragments","value":[{"kind":"identifier","text":"ZDKObjCAnonymous"}]},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCIdentity\/title","value":"ZDKObjCIdentity","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKObjCIdentity"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCIdentity\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}