{"sections":[],"metadata":{"externalID":"c:@M@ZendeskCoreSDK@objc(pl)IdentityMigration(im)getMigratedJwtIdentifier","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getMigratedJwtIdentifier","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"getMigratedJwtIdentifier"}],"role":"symbol","required":true,"modules":[{"name":"ZendeskCoreSDK"}],"symbolKind":"method","roleHeading":"Instance Method","title":"getMigratedJwtIdentifier()"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityMigration\/getMigratedJwtIdentifier()"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityMigration"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendeskcoresdk\/identitymigration\/getmigratedjwtidentifier()"]},{"paths":["\/documentation\/zendeskcoresdk\/identitymigration\/getmigratedjwtidentifier()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMigratedJwtIdentifier"},{"kind":"text","text":"() -> "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/IdentityMigration":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdentityMigration"}],"type":"topic","abstract":[],"navigatorTitle":[{"text":"IdentityMigration","kind":"identifier"}],"kind":"symbol","title":"IdentityMigration","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityMigration","role":"symbol","url":"\/documentation\/zendeskcoresdk\/identitymigration"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","url":"\/documentation\/zendeskcoresdk","kind":"symbol","title":"ZendeskCoreSDK"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/IdentityMigration/getMigratedJwtIdentifier()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMigratedJwtIdentifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","abstract":[],"required":true,"navigatorTitle":[{"text":"getMigratedJwtIdentifier","kind":"identifier"}],"kind":"symbol","title":"getMigratedJwtIdentifier()","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityMigration\/getMigratedJwtIdentifier()","role":"symbol","url":"\/documentation\/zendeskcoresdk\/identitymigration\/getmigratedjwtidentifier()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"getMigratedJwtIdentifier","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMigratedJwtIdentifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"getMigratedJwtIdentifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityMigration\/title","value":"IdentityMigration","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityMigration\/fragments","value":[{"kind":"identifier","text":"IdentityMigration"}],"op":"replace"},{"value":"getMigratedJwtIdentifier","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityMigration~1getMigratedJwtIdentifier()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityMigration~1getMigratedJwtIdentifier()\/fragments","value":[{"kind":"text","text":"- "},{"text":"getMigratedJwtIdentifier","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}