{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType","text":"IdentityType","preciseIdentifier":"c:@M@ZendeskCoreSDK@E@ZDKClassicIdentityType","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCAnonymous\/type","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCAnonymous"]]},"metadata":{"title":"type","symbolKind":"property","navigatorTitle":[{"text":"type","kind":"identifier"}],"modules":[{"name":"ZendeskCoreSDK"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@ZendeskCoreSDK@E@ZDKClassicIdentityType","kind":"typeIdentifier","text":"IdentityType"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKObjCAnonymous(py)type"},"kind":"symbol","variants":[{"paths":["\/documentation\/zendeskcoresdk\/zdkobjcanonymous\/type"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendeskcoresdk\/zdkobjcanonymous\/type"]}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"ZDKObjCIdentity.type","type":"codeVoice"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/IdentityType":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType","title":"IdentityType","type":"topic","url":"\/documentation\/zendeskcoresdk\/identitytype","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"IdentityType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IdentityType"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKObjCAnonymous/type":{"title":"type","type":"topic","navigatorTitle":[{"kind":"identifier","text":"type"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"text":"IdentityType","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskCoreSDK@E@ZDKClassicIdentityType"}],"url":"\/documentation\/zendeskcoresdk\/zdkobjcanonymous\/type","abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCAnonymous\/type","kind":"symbol","role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"type":"topic","role":"collection","title":"ZendeskCoreSDK","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","abstract":[],"kind":"symbol","url":"\/documentation\/zendeskcoresdk"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKObjCAnonymous":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKObjCAnonymous","kind":"symbol","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"ZDKObjCAnonymous","kind":"identifier"}],"url":"\/documentation\/zendeskcoresdk\/zdkobjcanonymous","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ZDKObjCAnonymous","kind":"identifier"}],"title":"ZDKObjCAnonymous"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"type","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"type"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType","text":"ZDKClassicIdentityType","preciseIdentifier":"c:@M@ZendeskCoreSDK@E@ZDKClassicIdentityType","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityType\/title","value":"ZDKClassicIdentityType","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityType\/fragments","value":[{"text":"ZDKClassicIdentityType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCAnonymous~1type\/title","value":"type"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCAnonymous~1type\/fragments","value":[{"text":"type","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCAnonymous\/title","value":"ZDKObjCAnonymous","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKObjCAnonymous\/fragments","value":[{"kind":"identifier","text":"ZDKObjCAnonymous"}],"op":"replace"}]}]}