{"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendeskcoresdk\/user\/name"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendeskcoresdk\/user\/name"]}],"abstract":[{"type":"text","text":"The user’s name"}],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"name":"ZendeskCoreSDK"}],"symbolKind":"property","title":"name","navigatorTitle":[{"text":"name","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUser(py)name"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User"]]},"identifier":{"url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/name","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/User/name":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"name","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","title":"name","url":"\/documentation\/zendeskcoresdk\/user\/name","abstract":[{"type":"text","text":"The user’s name"}],"navigatorTitle":[{"text":"name","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/name"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/User":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"User"}],"kind":"symbol","title":"User","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User","url":"\/documentation\/zendeskcoresdk\/user","abstract":[{"type":"text","text":"A user in Zendesk."}],"navigatorTitle":[{"kind":"identifier","text":"User"}],"role":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","role":"collection","url":"\/documentation\/zendeskcoresdk","kind":"symbol","abstract":[],"title":"ZendeskCoreSDK"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"name","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"name"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"name","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","value":"name","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User~1name\/title"},{"op":"replace","value":[{"text":"name","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User~1name\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User\/title","value":"ZDKClassicUser","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User\/fragments","value":[{"text":"ZDKClassicUser","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}