{"identifier":{"url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/warn","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Case","externalID":"c:@M@ZendeskCoreSDK@E@ZDKClassicLogLevel@ZDKClassicLogLevelWarn","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"warn","kind":"identifier"}],"symbolKind":"case","role":"symbol","title":"LogLevel.warn","navigatorTitle":[{"text":"ZDKClassicLogLevelWarn","kind":"identifier"}],"modules":[{"name":"ZendeskCoreSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"warn"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/zendeskcoresdk\/loglevel\/warn"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendeskcoresdk\/loglevel\/warn"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/LogLevel":{"title":"LogLevel","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LogLevel","kind":"identifier"}],"url":"\/documentation\/zendeskcoresdk\/loglevel","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel","type":"topic","abstract":[],"kind":"symbol"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"type":"topic","role":"collection","title":"ZendeskCoreSDK","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","abstract":[],"kind":"symbol","url":"\/documentation\/zendeskcoresdk"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/LogLevel/warn":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKClassicLogLevelWarn"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/warn","title":"LogLevel.warn","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"warn","kind":"identifier"}],"url":"\/documentation\/zendeskcoresdk\/loglevel\/warn"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKClassicLogLevelWarn"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"ZDKClassicLogLevelWarn","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ZDKClassicLogLevelWarn","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKClassicLogLevel","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel\/fragments","value":[{"text":"ZDKClassicLogLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel~1warn\/title","value":"ZDKClassicLogLevelWarn","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel~1warn\/fragments","op":"replace","value":[{"text":"ZDKClassicLogLevelWarn","kind":"identifier"}]}]}]}