{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterForPush"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/zendeskcoresdk\/zdkpushprovider\/unregisterforpush()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendeskcoresdk\/zdkpushprovider\/unregisterforpush()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider\/unregisterForPush()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Calls a push unregister endpoint with the stored device identifier"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterForPush"},{"kind":"text","text":"()"}],"title":"unregisterForPush()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicPushProvider(im)unregisterForPush","modules":[{"name":"ZendeskCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"unregisterForPush"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider"]]},"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKPushProvider/unregisterForPush()":{"role":"symbol","title":"unregisterForPush()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterForPush"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Calls a push unregister endpoint with the stored device identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider\/unregisterForPush()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unregisterForPush"}],"url":"\/documentation\/zendeskcoresdk\/zdkpushprovider\/unregisterforpush()"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"role":"collection","title":"ZendeskCoreSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKPushProvider":{"role":"symbol","title":"ZDKPushProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKPushProvider"}],"abstract":[{"type":"text","text":"An objective-c visible class for the Push Registration Provider"},{"type":"text","text":" "},{"type":"text","text":"Provider to register and unregister a device for push notifications."}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKPushProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ZDKPushProvider"}],"url":"\/documentation\/zendeskcoresdk\/zdkpushprovider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"unregisterForPush"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unregisterForPush"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"unregisterForPush"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKPushProvider~1unregisterForPush()\/title","value":"unregisterForPush"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKPushProvider~1unregisterForPush()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unregisterForPush"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKPushProvider\/title","value":"ZDKClassicPushProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKPushProvider\/fragments","value":[{"kind":"identifier","text":"ZDKClassicPushProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}