{"variants":[{"paths":["\/documentation\/zendeskcoresdk\/userfield\/regexp_for_validation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendeskcoresdk\/userfield\/regexp_for_validation"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserField\/regexp_for_validation"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"regexp_for_validation","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserField"]]},"sections":[],"abstract":[{"text":"regex of user field","type":"text"}],"metadata":{"externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUserField(py)regexp_for_validation","navigatorTitle":[{"kind":"identifier","text":"regexp_for_validation"}],"roleHeading":"Instance Property","symbolKind":"property","title":"regexp_for_validation","modules":[{"name":"ZendeskCoreSDK"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"regexp_for_validation"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol"},"kind":"symbol","references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","url":"\/documentation\/zendeskcoresdk","kind":"symbol","title":"ZendeskCoreSDK"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/UserField":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserField","kind":"symbol","url":"\/documentation\/zendeskcoresdk\/userfield","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UserField","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"User Field in Zendesk"}],"navigatorTitle":[{"kind":"identifier","text":"UserField"}],"title":"UserField","type":"topic"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/UserField/regexp_for_validation":{"abstract":[{"type":"text","text":"regex of user field"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/zendeskcoresdk\/userfield\/regexp_for_validation","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"regexp_for_validation"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"regexp_for_validation","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserField\/regexp_for_validation","title":"regexp_for_validation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"regexp_for_validation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"regexp_for_validation"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"regexp_for_validation"}]}]}},{"value":"ZDKClassicUserField","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserField\/title"},{"value":[{"text":"ZDKClassicUserField","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserField\/fragments","op":"replace"},{"value":"regexp_for_validation","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserField~1regexp_for_validation\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserField~1regexp_for_validation\/fragments","op":"replace","value":[{"text":"regexp_for_validation","kind":"identifier"}]}]}]}