{"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserField"]]},"abstract":[{"type":"text","text":"Options for the custom userfield. An array of ZDKCustomField objects"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"custom_field_options","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserFieldOption","text":"UserFieldOption","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUserFieldOption","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUserField(py)custom_field_options","role":"symbol","modules":[{"name":"ZendeskCoreSDK"}],"symbolKind":"property","title":"custom_field_options","navigatorTitle":[{"kind":"identifier","text":"custom_field_options"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"custom_field_options","kind":"identifier"},{"kind":"text","text":": ["},{"text":"UserFieldOption","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUserFieldOption","kind":"typeIdentifier"},{"text":"]?","kind":"text"}]},"identifier":{"url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserField\/custom_field_options","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendeskcoresdk\/userfield\/custom_field_options"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendeskcoresdk\/userfield\/custom_field_options"]}],"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"title":"ZendeskCoreSDK","url":"\/documentation\/zendeskcoresdk","type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","abstract":[]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/UserField":{"kind":"symbol","type":"topic","abstract":[{"text":"User Field in Zendesk","type":"text"}],"title":"UserField","role":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserField","url":"\/documentation\/zendeskcoresdk\/userfield","navigatorTitle":[{"text":"UserField","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserField"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/UserFieldOption":{"url":"\/documentation\/zendeskcoresdk\/userfieldoption","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserFieldOption","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserFieldOption","navigatorTitle":[{"text":"UserFieldOption","kind":"identifier"}],"kind":"symbol","title":"UserFieldOption","abstract":[{"text":"Dropdown userfields can contain User fields options which describe an option in the","type":"text"},{"type":"text","text":" "},{"text":"dropdown","type":"text"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/UserField/custom_field_options":{"kind":"symbol","role":"symbol","title":"custom_field_options","type":"topic","navigatorTitle":[{"text":"custom_field_options","kind":"identifier"}],"url":"\/documentation\/zendeskcoresdk\/userfield\/custom_field_options","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"custom_field_options"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUserFieldOption","text":"UserFieldOption"},{"kind":"text","text":"]?"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserField\/custom_field_options","abstract":[{"type":"text","text":"Options for the custom userfield. An array of ZDKCustomField objects"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"custom_field_options"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"custom_field_options"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<ZDKClassicUserFieldOption *>"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"custom_field_options"}]}]}},{"value":"ZDKClassicUserField","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserField\/title"},{"value":[{"kind":"identifier","text":"ZDKClassicUserField"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserField\/fragments"},{"value":"ZDKClassicUserFieldOption","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserFieldOption\/title"},{"op":"replace","value":[{"text":"ZDKClassicUserFieldOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserFieldOption\/fragments"},{"op":"replace","value":"custom_field_options","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserField~1custom_field_options\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserField~1custom_field_options\/fragments","value":[{"text":"custom_field_options","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}