{"kind":"symbol","variants":[{"paths":["\/documentation\/zendeskcoresdk\/identitytype\/anonymous"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendeskcoresdk\/identitytype\/anonymous"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType"]]},"metadata":{"externalID":"c:@M@ZendeskCoreSDK@E@ZDKClassicIdentityType@ZDKClassicIdentityTypeAnonymous","roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"ZDKClassicIdentityTypeAnonymous","kind":"identifier"}],"modules":[{"name":"ZendeskCoreSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"anonymous"}],"symbolKind":"case","title":"IdentityType.anonymous"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType\/anonymous"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"anonymous","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/IdentityType/anonymous":{"abstract":[],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/zendeskcoresdk\/identitytype\/anonymous","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"anonymous","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKClassicIdentityTypeAnonymous","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType\/anonymous","title":"IdentityType.anonymous"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","url":"\/documentation\/zendeskcoresdk","kind":"symbol","title":"ZendeskCoreSDK"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/IdentityType":{"kind":"symbol","role":"symbol","title":"IdentityType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IdentityType"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityType","url":"\/documentation\/zendeskcoresdk\/identitytype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"IdentityType","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"ZDKClassicIdentityTypeAnonymous","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"text":"ZDKClassicIdentityTypeAnonymous","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"ZDKClassicIdentityTypeAnonymous","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityType~1anonymous\/title","value":"ZDKClassicIdentityTypeAnonymous","op":"replace"},{"value":[{"text":"ZDKClassicIdentityTypeAnonymous","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityType~1anonymous\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityType\/title","value":"ZDKClassicIdentityType","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityType\/fragments","op":"replace","value":[{"text":"ZDKClassicIdentityType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}