{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User"]]},"metadata":{"roleHeading":"Instance Property","role":"symbol","title":"user_fields","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"user_fields","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"modules":[{"name":"ZendeskCoreSDK"}],"externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUser(py)user_fields","navigatorTitle":[{"kind":"identifier","text":"user_fields"}],"symbolKind":"property"},"abstract":[{"type":"text","text":"User fields for this user as a dictionary with the key being the name of the user field"},{"text":" ","type":"text"},{"type":"text","text":"and the corresponding value being the value of the user field set for this user."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendeskcoresdk\/user\/user_fields"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/zendeskcoresdk\/user\/user_fields"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"user_fields","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/user_fields","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/User/user_fields":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User\/user_fields","type":"topic","navigatorTitle":[{"text":"user_fields","kind":"identifier"}],"url":"\/documentation\/zendeskcoresdk\/user\/user_fields","title":"user_fields","role":"symbol","abstract":[{"text":"User fields for this user as a dictionary with the key being the name of the user field","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and the corresponding value being the value of the user field set for this user."}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"user_fields"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]","kind":"text"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"role":"collection","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","kind":"symbol","url":"\/documentation\/zendeskcoresdk","abstract":[],"title":"ZendeskCoreSDK"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/User":{"navigatorTitle":[{"text":"User","kind":"identifier"}],"title":"User","kind":"symbol","url":"\/documentation\/zendeskcoresdk\/user","type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/User","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"User","kind":"identifier"}],"abstract":[{"type":"text","text":"A user in Zendesk."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"user_fields"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"user_fields","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>"},{"kind":"text","text":" * "},{"text":"user_fields","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User~1user_fields\/title","value":"user_fields"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User~1user_fields\/fragments","value":[{"text":"user_fields","kind":"identifier"}],"op":"replace"},{"value":"ZDKClassicUser","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKClassicUser"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1User\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}