{"metadata":{"title":"LogLevel.verbose","role":"symbol","navigatorTitle":[{"text":"ZDKClassicLogLevelVerbose","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@ZendeskCoreSDK@E@ZDKClassicLogLevel@ZDKClassicLogLevelVerbose","modules":[{"name":"ZendeskCoreSDK"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verbose","kind":"identifier"}],"symbolKind":"case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/verbose"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel"]]},"variants":[{"paths":["\/documentation\/zendeskcoresdk\/loglevel\/verbose"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendeskcoresdk\/loglevel\/verbose"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verbose","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"title":"ZendeskCoreSDK","url":"\/documentation\/zendeskcoresdk","type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","abstract":[]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/LogLevel":{"title":"LogLevel","url":"\/documentation\/zendeskcoresdk\/loglevel","type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LogLevel"}],"navigatorTitle":[{"kind":"identifier","text":"LogLevel"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/LogLevel/verbose":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"verbose","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKClassicLogLevelVerbose","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/LogLevel\/verbose","title":"LogLevel.verbose","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk\/loglevel\/verbose","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ZDKClassicLogLevelVerbose"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"ZDKClassicLogLevelVerbose","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"ZDKClassicLogLevelVerbose","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"value":"ZDKClassicLogLevel","op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel\/title"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel\/fragments","op":"replace","value":[{"text":"ZDKClassicLogLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel~1verbose\/title","op":"replace","value":"ZDKClassicLogLevelVerbose"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1LogLevel~1verbose\/fragments","value":[{"kind":"identifier","text":"ZDKClassicLogLevelVerbose"}]}]}]}