{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdentityMigration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/zendeskcoresdk\/identitymigration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/zendeskcoresdk\/identitymigration"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityMigration","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityMigration\/getMigratedAnonymousEmail()","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityMigration\/getMigratedAnonymousName()","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityMigration\/getMigratedJwtIdentifier()"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdentityMigration"}],"title":"IdentityMigration","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@ZendeskCoreSDK@objc(pl)IdentityMigration","modules":[{"name":"ZendeskCoreSDK"}],"navigatorTitle":[{"kind":"identifier","text":"IdentityMigration"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK"]]},"references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/IdentityMigration":{"role":"symbol","title":"IdentityMigration","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdentityMigration"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityMigration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IdentityMigration"}],"url":"\/documentation\/zendeskcoresdk\/identitymigration"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/IdentityMigration/getMigratedJwtIdentifier()":{"navigatorTitle":[{"kind":"identifier","text":"getMigratedJwtIdentifier"}],"role":"symbol","title":"getMigratedJwtIdentifier()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMigratedJwtIdentifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityMigration\/getMigratedJwtIdentifier()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/zendeskcoresdk\/identitymigration\/getmigratedjwtidentifier()"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/IdentityMigration/getMigratedAnonymousName()":{"navigatorTitle":[{"kind":"identifier","text":"getMigratedAnonymousName"}],"role":"symbol","title":"getMigratedAnonymousName()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMigratedAnonymousName"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityMigration\/getMigratedAnonymousName()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/zendeskcoresdk\/identitymigration\/getmigratedanonymousname()"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/IdentityMigration/getMigratedAnonymousEmail()":{"navigatorTitle":[{"kind":"identifier","text":"getMigratedAnonymousEmail"}],"role":"symbol","title":"getMigratedAnonymousEmail()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getMigratedAnonymousEmail"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityMigration\/getMigratedAnonymousEmail()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/zendeskcoresdk\/identitymigration\/getmigratedanonymousemail()"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"role":"collection","title":"ZendeskCoreSDK","abstract":[],"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","kind":"symbol","type":"topic","url":"\/documentation\/zendeskcoresdk"},"doc://com.zendesk.ZendeskCoreSDK/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"IdentityMigration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IdentityMigration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"IdentityMigration"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityMigration\/getMigratedAnonymousEmail()","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityMigration\/getMigratedAnonymousName()","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/IdentityMigration\/getMigratedJwtIdentifier()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.zendesk.ZendeskCoreSDK\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IdentityMigration"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityMigration\/title","value":"IdentityMigration"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityMigration\/fragments","value":[{"kind":"identifier","text":"IdentityMigration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityMigration~1getMigratedJwtIdentifier()\/title","value":"getMigratedJwtIdentifier"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityMigration~1getMigratedJwtIdentifier()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMigratedJwtIdentifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityMigration~1getMigratedAnonymousName()\/title","value":"getMigratedAnonymousName"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityMigration~1getMigratedAnonymousName()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMigratedAnonymousName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityMigration~1getMigratedAnonymousEmail()\/title","value":"getMigratedAnonymousEmail"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1IdentityMigration~1getMigratedAnonymousEmail()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getMigratedAnonymousEmail"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}