{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKUserProvider"]]},"metadata":{"externalID":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUserProvider(im)getUserFieldsWithCompletion:","symbolKind":"method","title":"getUserFieldsWithCompletion(_:)","modules":[{"name":"ZendeskCoreSDK"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserFieldsWithCompletion"},{"text":"((([","kind":"text"},{"text":"UserField","kind":"typeIdentifier","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUserField"},{"text":"], ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":"))","kind":"text"}],"navigatorTitle":[{"text":"getUserFieldsWithCompletion:","kind":"identifier"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/zendeskcoresdk\/zdkuserprovider\/getuserfieldswithcompletion(_:)"]},{"paths":["\/documentation\/zendeskcoresdk\/zdkuserprovider\/getuserfieldswithcompletion(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Gets all user fields available for an account instance.","type":"text"}],"identifier":{"url":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKUserProvider\/getUserFieldsWithCompletion(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getUserFieldsWithCompletion"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" (([","kind":"text"},{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserField","text":"UserField","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUserField","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":"))"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"completion: Returns an array of userfield objects if successful with a nil error.","type":"text"}]}]}]}]}],"kind":"symbol","references":{"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKUserProvider/getUserFieldsWithCompletion(_:)":{"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserFieldsWithCompletion"},{"text":"((([","kind":"text"},{"text":"UserField","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicUserField","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":"))"}],"title":"getUserFieldsWithCompletion(_:)","navigatorTitle":[{"text":"getUserFieldsWithCompletion:","kind":"identifier"}],"url":"\/documentation\/zendeskcoresdk\/zdkuserprovider\/getuserfieldswithcompletion(_:)","abstract":[{"type":"text","text":"Gets all user fields available for an account instance."}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKUserProvider\/getUserFieldsWithCompletion(_:)"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK":{"type":"topic","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK","role":"collection","url":"\/documentation\/zendeskcoresdk","kind":"symbol","abstract":[],"title":"ZendeskCoreSDK"},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/ZDKUserProvider":{"identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/ZDKUserProvider","title":"ZDKUserProvider","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ZDKUserProvider"}],"role":"symbol","navigatorTitle":[{"text":"ZDKUserProvider","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/zendeskcoresdk\/zdkuserprovider","abstract":[{"text":"An objective-c visible class for the User Provider","type":"text"}]},"doc://com.zendesk.ZendeskCoreSDK/documentation/ZendeskCoreSDK/UserField":{"title":"UserField","identifier":"doc:\/\/com.zendesk.ZendeskCoreSDK\/documentation\/ZendeskCoreSDK\/UserField","abstract":[{"text":"User Field in Zendesk","type":"text"}],"navigatorTitle":[{"text":"UserField","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/zendeskcoresdk\/userfield","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserField"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"getUserFieldsWithCompletion:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"getUserFieldsWithCompletion:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"getUserFieldsWithCompletion:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*Q$objc(cs)NSArray#*$objc(cs)NSError)","text":"void (^)(NSArray<ZDKClassicUserField *> *, NSError *)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKUserProvider~1getUserFieldsWithCompletion(_:)\/title","value":"getUserFieldsWithCompletion:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"getUserFieldsWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKUserProvider~1getUserFieldsWithCompletion(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKUserProvider\/title","op":"replace","value":"ZDKClassicUserProvider"},{"value":[{"text":"ZDKClassicUserProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1ZDKUserProvider\/fragments"},{"value":"ZDKClassicUserField","path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserField\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.ZendeskCoreSDK~1documentation~1ZendeskCoreSDK~1UserField\/fragments","op":"replace","value":[{"text":"ZDKClassicUserField","kind":"identifier"}]}]}]}